### ISSUE TITLE
适配24.6

### ISSUE THREAD

**Issue by z-henry** [Pik-4/HsMod#10]
除了函数名更改还有一个patch失效了`Hearthstone.Progression.RewardTrack.UpdateStatus`，从入参推测应该是将`Hearthstone.Progression.RewardTrack.RewardStatus.GRANTED`单独封装成了函数`Hearthstone.Progression.RewardTrack.HandleRewardGranted`

**Comment by Pik-4** [comment]
尝试修了一下，观察一段时间看看
