### ISSUE TITLE
战棋换肤似乎有bug

### ISSUE THREAD

**Issue by joe98107** [Pik-4/HsMod#101]
战棋换肤后会导致游戏匹配卡死，具体为匹配滚筒一直滚，无法进入对局，战棋选择英雄后卡死

**Comment by joe98107** [comment]
战棋换肤有bug先注释掉了
`# 皮肤映射表
# 说明：主要用作英雄（酒馆、对战）类皮肤替换；按下F4会在BepInEx目录下生成当前全部皮肤信息；
# 格式：原始皮肤:替换皮肤（:为半角字符）；下一行是一个样例(玛法里奥·怒风替换成大导师玛法里奥)，可以删除
#      亦支持a:b,c,d这种多值映射，实现随机皮肤。
274:60375,101768,68368,80187,93966
78065:110718,112782,112708,114333,100115,106274,101700,97869,111247,93448
56550:108423,110719,101770,89939,114192,101679,114339,108382,98361,71331,77246,108382,93980,62491
31:60335,105081,97862,111233,108384,112517,2826,61597,110712,93762,89942,77247
637:108417,79963,62772,112702,111241,108389,84141,39117,93976,101775,71723,61598,77253,60157,82519,98729,2829
671:67519,72682,97873,61596,108385,46116,109343,2827,53187,112745,77249,83395,103765,114332,83826,108385,61886,111242,94026
813:67523,79975,112705,103777,101701,93970,110727,107730,41887,67710,112785,54816,89937,111231,77251,108418,105082,101648,107730
930:67522,101699,79973,97870,80183,101654,112526,103776,84090,109340,78586,67846,107748
1066:112762,112713,101641,83411,53237,112742,111235,108420,55963,101641,105071,74586,60673,71058,77248
893:103775,98723,103104,64685,51834,112750,77254,108386,93724,71324,97865,77254
7:67521,101672,79966,61923,84156,58787,117487,107749,98727,89927,101666,61595,78174,111238,2828
# 101345:102493
# 64485:82053,78753,107787
# 66196:96565
# 71458:111546
# 57634:77186
# 80832:102868,103813,97929
# 60370:102872,112470
# 60213:89702,82059
# 58021:111061
# 58535:104418,115377,96581,97932
# 97186:111295,107782,104414
# 61912:98813
# 73940:111293,98811
# 104982:112468
# 59807:98795,112483
# 86291:102919,107783
# 86013:103814,115390
# 77516:106654,111060,97920
# 104981:112469
# 68129:115380
# 71916:115388,103824,96584
# 57929:95315,82514,75170
# 74646:107784
# 77987:115387,98808,112484
# 98726:112476,103826
# 62268:102874,96566
# 82110:97927,102917
# 64403:107785,96582
# 62242:99061,80568
# 59805:96577,103821
# 58044:111294,98801
# 58024:97931,98797
# 63602:96575,103808
# 79719:98794,102870,103802
# 89293:115382,104419,105061
# 64480:103797
# 59397:112481,115379
# 74631:96564,106628
# 96870:102876,111297,114038
# 92960:103820,102494,111661,105063
# 80239:115375
# 60214:96576,99062
# 66483:102861,107789
# 64400:96611,115386,111545,96583
# 57944:106657,102495,95328,99059
# 67356:97921,103815
# 84867:103807,115391,107780
# 76562:102864
# 76521:103817,98798
# 97813:112482,107781
# 63604:83646,78752
# 67553:96613,97925,112478
# 60369:98796
# 63319:106655,102918,105059
# 58534:97924
# 71463:96572
# 58027:102913,103818,96569
# 70956:92182,98810,114039,112477
# 70838:99063,103801,102867,96561,106256
# 57947:96579,105060
# 57892:111064,96580,115376
# 75702:94871
# 61914:106255,82055
# 61490:96567,98807
# 85125:102863,103822,96612
# 79615:89704,103819,98812
# 57924:96571,115383
# 59831:102869,96578
# 59814:96427,102496
# 57946:96614,97923,96573
# 60366:102491,96560
# 60362:107786,82056
# 59806:106658,103816
# 57633:89705,115389,111663
# 79618:103803,104416
# 60211:94535,77180
# 60367:97928,114041,112480
# 80247:98809,112485
# 60372:77181
# 71454:111662,96568
# 105314:111660
# 63601:105062,96574
# 61489:115378,107788
# 57891:97926,111659
# 81569:111296,103825,96615
# 58435:98800
# 57635:106656,96570,98799
# 62266:111549
# 71908:99060,111548
# 61910:83638,82060,89700,94526
# 61488:102871,111547,103798
# 60212:89703
# 103477:103823
# 97922:102923,97922
# 57893:112479,97930
# 64475:114040
# 57110:105091,105056,105058,104480,111302,111657,115369,104479,105057,114043`

**Comment by joe98107** [comment]
战棋换肤有bug就注释掉了
# 皮肤映射表
# 说明：主要用作英雄（酒馆、对战）类皮肤替换；按下F4会在BepInEx目录下生成当前全部皮肤信息；
# 格式：原始皮肤:替换皮肤（:为半角字符）；下一行是一个样例(玛法里奥·怒风替换成大导师玛法里奥)，可以删除
#      亦支持a:b,c,d这种多值映射，实现随机皮肤。
274:60375,101768,68368,80187,93966
78065:110718,112782,112708,114333,100115,106274,101700,97869,111247,93448
56550:108423,110719,101770,89939,114192,101679,114339,108382,98361,71331,77246,108382,93980,62491
31:60335,105081,97862,111233,108384,112517,2826,61597,110712,93762,89942,77247
637:108417,79963,62772,112702,111241,108389,84141,39117,93976,101775,71723,61598,77253,60157,82519,98729,2829
671:67519,72682,97873,61596,108385,46116,109343,2827,53187,112745,77249,83395,103765,114332,83826,108385,61886,111242,94026
813:67523,79975,112705,103777,101701,93970,110727,107730,41887,67710,112785,54816,89937,111231,77251,108418,105082,101648,107730
930:67522,101699,79973,97870,80183,101654,112526,103776,84090,109340,78586,67846,107748
1066:112762,112713,101641,83411,53237,112742,111235,108420,55963,101641,105071,74586,60673,71058,77248
893:103775,98723,103104,64685,51834,112750,77254,108386,93724,71324,97865,77254
7:67521,101672,79966,61923,84156,58787,117487,107749,98727,89927,101666,61595,78174,111238,2828
# 101345:102493
# 64485:82053,78753,107787
# 66196:96565
# 71458:111546
# 57634:77186
# 80832:102868,103813,97929
# 60370:102872,112470
# 60213:89702,82059
# 58021:111061
# 58535:104418,115377,96581,97932
# 97186:111295,107782,104414
# 61912:98813
# 73940:111293,98811
# 104982:112468
# 59807:98795,112483
# 86291:102919,107783
# 86013:103814,115390
# 77516:106654,111060,97920
# 104981:112469
# 68129:115380
# 71916:115388,103824,96584
# 57929:95315,82514,75170
# 74646:107784
# 77987:115387,98808,112484
# 98726:112476,103826
# 62268:102874,96566
# 82110:97927,102917
# 64403:107785,96582
# 62242:99061,80568
# 59805:96577,103821
# 58044:111294,98801
# 58024:97931,98797
# 63602:96575,103808
# 79719:98794,102870,103802
# 89293:115382,104419,105061
# 64480:103797
# 59397:112481,115379
# 74631:96564,106628
# 96870:102876,111297,114038
# 92960:103820,102494,111661,105063
# 80239:115375
# 60214:96576,99062
# 66483:102861,107789
# 64400:96611,115386,111545,96583
# 57944:106657,102495,95328,99059
# 67356:97921,103815
# 84867:103807,115391,107780
# 76562:102864
# 76521:103817,98798
# 97813:112482,107781
# 63604:83646,78752
# 67553:96613,97925,112478
# 60369:98796
# 63319:106655,102918,105059
# 58534:97924
# 71463:96572
# 58027:102913,103818,96569
# 70956:92182,98810,114039,112477
# 70838:99063,103801,102867,96561,106256
# 57947:96579,105060
# 57892:111064,96580,115376
# 75702:94871
# 61914:106255,82055
# 61490:96567,98807
# 85125:102863,103822,96612
# 79615:89704,103819,98812
# 57924:96571,115383
# 59831:102869,96578
# 59814:96427,102496
# 57946:96614,97923,96573
# 60366:102491,96560
# 60362:107786,82056
# 59806:106658,103816
# 57633:89705,115389,111663
# 79618:103803,104416
# 60211:94535,77180
# 60367:97928,114041,112480
# 80247:98809,112485
# 60372:77181
# 71454:111662,96568
# 105314:111660
# 63601:105062,96574
# 61489:115378,107788
# 57891:97926,111659
# 81569:111296,103825,96615
# 58435:98800
# 57635:106656,96570,98799
# 62266:111549
# 71908:99060,111548
# 61910:83638,82060,89700,94526
# 61488:102871,111547,103798
# 60212:89703
# 103477:103823
# 97922:102923,97922
# 57893:112479,97930
# 64475:114040
# 57110:105091,105056,105058,104480,111302,111657,115369,104479,105057,114043

**Comment by joe98107** [comment]
```
# 皮肤映射表
# 说明：主要用作英雄（酒馆、对战）类皮肤替换；按下F4会在BepInEx目录下生成当前全部皮肤信息；
# 格式：原始皮肤:替换皮肤（:为半角字符）；下一行是一个样例(玛法里奥·怒风替换成大导师玛法里奥)，可以删除
#      亦支持a:b,c,d这种多值映射，实现随机皮肤。
274:60375,101768,68368,80187,93966
78065:110718,112782,112708,114333,100115,106274,101700,97869,111247,93448
56550:108423,110719,101770,89939,114192,101679,114339,108382,98361,71331,77246,108382,93980,62491
31:60335,105081,97862,111233,108384,112517,2826,61597,110712,93762,89942,77247
637:108417,79963,62772,112702,111241,108389,84141,39117,93976,101775,71723,61598,77253,60157,82519,98729,2829
671:67519,72682,97873,61596,108385,46116,109343,2827,53187,112745,77249,83395,103765,114332,83826,108385,61886,111242,94026
813:67523,79975,112705,103777,101701,93970,110727,107730,41887,67710,112785,54816,89937,111231,77251,108418,105082,101648,107730
930:67522,101699,79973,97870,80183,101654,112526,103776,84090,109340,78586,67846,107748
1066:112762,112713,101641,83411,53237,112742,111235,108420,55963,101641,105071,74586,60673,71058,77248
893:103775,98723,103104,64685,51834,112750,77254,108386,93724,71324,97865,77254
7:67521,101672,79966,61923,84156,58787,117487,107749,98727,89927,101666,61595,78174,111238,2828
# 101345:102493
# 64485:82053,78753,107787
# 66196:96565
# 71458:111546
# 57634:77186
# 80832:102868,103813,97929
# 60370:102872,112470
# 60213:89702,82059
# 58021:111061
# 58535:104418,115377,96581,97932
# 97186:111295,107782,104414
# 61912:98813
# 73940:111293,98811
# 104982:112468
# 59807:98795,112483
# 86291:102919,107783
# 86013:103814,115390
# 77516:106654,111060,97920
# 104981:112469
# 68129:115380
# 71916:115388,103824,96584
# 57929:95315,82514,75170
# 74646:107784
# 77987:115387,98808,112484
# 98726:112476,103826
# 62268:102874,96566
# 82110:97927,102917
# 64403:107785,96582
# 62242:99061,80568
# 59805:96577,103821
# 58044:111294,98801
# 58024:97931,98797
# 63602:96575,103808
# 79719:98794,102870,103802
# 89293:115382,104419,105061
# 64480:103797
# 59397:112481,115379
# 74631:96564,106628
# 96870:102876,111297,114038
# 92960:103820,102494,111661,105063
# 80239:115375
# 60214:96576,99062
# 66483:102861,107789
# 64400:96611,115386,111545,96583
# 57944:106657,102495,95328,99059
# 67356:97921,103815
# 84867:103807,115391,107780
# 76562:102864
# 76521:103817,98798
# 97813:112482,107781
# 63604:83646,78752
# 67553:96613,97925,112478
# 60369:98796
# 63319:106655,102918,105059
# 58534:97924
# 71463:96572
# 58027:102913,103818,96569
# 70956:92182,98810,114039,112477
# 70838:99063,103801,102867,96561,106256
# 57947:96579,105060
# 57892:111064,96580,115376
# 75702:94871
# 61914:106255,82055
# 61490:96567,98807
# 85125:102863,103822,96612
# 79615:89704,103819,98812
# 57924:96571,115383
# 59831:102869,96578
# 59814:96427,102496
# 57946:96614,97923,96573
# 60366:102491,96560
# 60362:107786,82056
# 59806:106658,103816
# 57633:89705,115389,111663
# 79618:103803,104416
# 60211:94535,77180
# 60367:97928,114041,112480
# 80247:98809,112485
# 60372:77181
# 71454:111662,96568
# 105314:111660
# 63601:105062,96574
# 61489:115378,107788
# 57891:97926,111659
# 81569:111296,103825,96615
# 58435:98800
# 57635:106656,96570,98799
# 62266:111549
# 71908:99060,111548
# 61910:83638,82060,89700,94526
# 61488:102871,111547,103798
# 60212:89703
# 103477:103823
# 97922:102923,97922
# 57893:112479,97930
# 64475:114040
# 57110:105091,105056,105058,104480,111302,111657,115369,104479,105057,114043
```

**Comment by tuyile-icu** [comment]
应该是这个皮肤映射关系有错误，我遇到过，改掉就正常了

**Comment by joe98107** [comment]
> 应该是这个皮肤映射关系有错误，我遇到过，改掉就正常了

映射表语法上似乎没什么问题，还是我老眼昏花一个英雄的皮肤映射到另一个上了？

**Comment by joe98107** [comment]
找到了，是最后一个bob的映射，删掉就行了

**Comment by catshitz** [comment]
> 找到了，是最后一个bob的映射，删掉就行了

> 战棋换肤后会导致游戏匹配卡死，具体为匹配滚筒一直滚，无法进入对局，战棋选择英雄后卡死

我问题一模一样 问题是默认鲍勃57110 只要选了就一并偏好117409和117425，没法单选，要么我单选一个104477，不管咋样，只要有酒保替换就会出现天梯无限找势均力敌的对手，要么进去一直卡在开局界面头像刚到位置，牌库为空疲劳0，这个状态，只能手动认输然后重开游戏。

相当于现在酒保鲍勃的皮肤根本就不能替换么？

**Comment by freechao123** [comment]
> 应该是这个皮肤映射关系有错误，我遇到过，改掉就正常了

棋盘和打击特效可以改吗

**Comment by freechao123** [comment]
> > 应该是这个皮肤映射关系有错误，我遇到过，改掉就正常了
> 
> 映射表语法上似乎没什么问题，还是我老眼昏花一个英雄的皮肤映射到另一个上了？

棋盘和打击特效可以改吗
