### ISSUE TITLE
#8 issues happens again on Mac due to newer version of BepInEx 5.4.23.2

### ISSUE THREAD

**Issue by alanzxr** [Pik-4/HsMod#103]
Set HsMod.config to true already.

是否启用插件（修改该选项后建议重启炉石）
Setting type: Boolean
Default value: false
HsMod状态 = true

terminal output:
Failed to hook jit_init_version, ignoring it. Error: no such function: mono_jit_init_version
[UnityMemory] Configuration Parameters - Can be set up in boot.config
    "memorysetup-bucket-allocator-granularity=16"
    "memorysetup-bucket-allocator-bucket-count=8"
    "memorysetup-bucket-allocator-block-size=4194304"
    "memorysetup-bucket-allocator-block-count=1"
    "memorysetup-main-allocator-block-size=16777216"
    "memorysetup-thread-allocator-block-size=16777216"
    "memorysetup-gfx-main-allocator-block-size=16777216"
    "memorysetup-gfx-thread-allocator-block-size=16777216"
    "memorysetup-cache-allocator-block-size=4194304"
    "memorysetup-typetree-allocator-block-size=2097152"
    "memorysetup-profiler-bucket-allocator-granularity=16"
    "memorysetup-profiler-bucket-allocator-bucket-count=8"
    "memorysetup-profiler-bucket-allocator-block-size=4194304"
    "memorysetup-profiler-bucket-allocator-block-count=1"
    "memorysetup-profiler-allocator-block-size=16777216"
    "memorysetup-profiler-editor-allocator-block-size=1048576"
    "memorysetup-temp-allocator-size-main=4194304"
    "memorysetup-job-temp-allocator-block-size=2097152"
    "memorysetup-job-temp-allocator-block-size-background=1048576"
    "memorysetup-job-temp-allocator-reduction-small-platforms=262144"
    "memorysetup-temp-allocator-size-background-worker=32768"
    "memorysetup-temp-allocator-size-job-worker=262144"
    "memorysetup-temp-allocator-size-preload-manager=262144"
    "memorysetup-temp-allocator-size-nav-mesh-worker=65536"
    "memorysetup-temp-allocator-size-audio-worker=65536"
    "memorysetup-temp-allocator-size-cloud-worker=32768"
    "memorysetup-temp-allocator-size-gfx=262144"

**Comment by alanzxr** [comment]
windows version runs well

**Comment by alanzxr** [comment]
For China server: token should be retrieved via account.battlenet.com.cn/login/zh-cn/?app=wtcg
so maybe it is the wrong setting of Env = cn.actural.battle.net in client.config file?

**Comment by Pik-4** [comment]
env取决于token的前两个字符+.actual.battle.net，中国大陆地区的除外（中国大陆地区（中国大陆是cn.actual.battlenet.com.cn）。
我没有Mac设备，之前Linux是基于旧版unix测试。

**Comment by alanzxr** [comment]
Still unable to login, I have fixed cn.actual.battlenet.com.cn, another place the problem may happen is:
Edit the run_bepinex.sh file replacing the line export DOORSTOP_CORLIB_OVERRIDE_PATH=""with DOORSTOP_CORLIB_OVERRIDE_PATH="$BASEDIR/BepInEx/unstripped_corlib"
in the newest version 5.4.23.2 run_bepinex.sh, there is no DOORSTOP_CORLIB_OVERRIDE_PATH or $BASEDIR defined, I just modified dll_search_path_override="" as the windows version "BepInEx/unstripped_corlib". Should I also modify the following ENV variables?

```
export DOORSTOP_ENABLED="$enabled"
export DOORSTOP_TARGET_ASSEMBLY="$target_assembly"
export DOORSTOP_IGNORE_DISABLED_ENV="$ignore_disable_switch"
export DOORSTOP_MONO_DLL_SEARCH_PATH_OVERRIDE="$dll_search_path_override"
export DOORSTOP_MONO_DEBUG_ENABLED="$debug_enable"
export DOORSTOP_MONO_DEBUG_ADDRESS="$debug_address"
export DOORSTOP_MONO_DEBUG_SUSPEND="$debug_suspend"
export DOORSTOP_CLR_RUNTIME_CORECLR_PATH="$coreclr_path.$lib_extension"
export DOORSTOP_CLR_CORLIB_DIR="$corlib_dir"
```

I guess DOORSTOP_MONO_DLL_SEARCH_PATH_OVERRIDE and DOORSTOP_CLR_CORLIB_DIR should also be "BepInEx/unstripped_corlib"?

**Comment by alanzxr** [comment]
BepInEx/LogOutput.log:
```
[Warning:HsMod.MyLogger] Patcher => Patched 0 methods
[Error  :HsMod.MyLogger] PatchMisc => Could not load type AntiCheatSDK.AntiCheatManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null) 

[Error  :HsMod.MyLogger] HsMod patch failed!
```

**Comment by Pik-4** [comment]
> BepInEx/LogOutput.log:
> 
> ```
> [Warning:HsMod.MyLogger] Patcher => Patched 0 methods
> [Error  :HsMod.MyLogger] PatchMisc => Could not load type AntiCheatSDK.AntiCheatManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null) 
> 
> [Error  :HsMod.MyLogger] HsMod patch failed!
> 
> [Message:   BepInEx] Chainloader startup complete
> [Info   : Unity Log] Application paused: False
> [Info   :     HsMod] Plugin HsMod is started!
> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> Stack trace:
> HsMod.Plugin.Start () (at <835ade09cf404ad28d28831fe7a32096>:0)
> 
> [Error  : Unity Log] [Services] [ServiceLocator] Service Locator Shutdown Complete. Some services are in failure state.
> ```

Try 6.5.2.1.

**Comment by xupeng-faker** [comment]
MAC有完整解决流程吗？ 按照你的步骤走下去了

**Comment by alanzxr** [comment]
> > BepInEx/LogOutput.log:
> > ```
> > [Warning:HsMod.MyLogger] Patcher => Patched 0 methods
> > [Error  :HsMod.MyLogger] PatchMisc => Could not load type AntiCheatSDK.AntiCheatManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null) 
> > 
> > [Error  :HsMod.MyLogger] HsMod patch failed!
> > 
> > [Message:   BepInEx] Chainloader startup complete
> > [Info   : Unity Log] Application paused: False
> > [Info   :     HsMod] Plugin HsMod is started!
> > [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> > Stack trace:
> > HsMod.Plugin.Start () (at <835ade09cf404ad28d28831fe7a32096>:0)
> > 
> > [Error  : Unity Log] [Services] [ServiceLocator] Service Locator Shutdown Complete. Some services are in failure state.
> > ```
> 
> Try 6.5.2.3.

6.5.2.3 works! Thanks.

**Comment by alanzxr** [comment]
> MAC有完整解决流程吗？ 按照你的步骤走下去了

Try the latest 6.5.2.3 HsMod and follow the modified steps mentioned above. I can help if needed.

**Comment by xupeng-faker** [comment]
thanks, 如何修改 HsMod.cfg文件，我没有找到这个HsMod.cfg

**Comment by httpsColon** [comment]
> thanks, 如何修改 HsMod.cfg文件，我没有找到这个HsMod.cfg

"D:\Program Files (x86)\Hearthstone\BepInEx\config\HsMod.cfg"
