### ISSUE TITLE
Please update the Mac version for BepInEx 5.4.23.2

### ISSUE THREAD

**Issue by schengx** [Pik-4/HsMod#104]
The game just suddenly crushed without any notification.

Also the steps for installing Mac HsMod work for BepInEx 5.4.22 rather than the latest version, please notice that some of the content in run_bepinex.sh has been changed for the Mac version.

I have a Windows PC and this mod works well on it, I appreciate your work but an update for the Mac version would be nice.

**Comment by schengx** [comment]
`[Message:   BepInEx] BepInEx 5.4.23.2 - Hearthstone (11/10/2024 05:49:16)
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, MacOS
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInExConfigManager.Mono.Patcher 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2021.3.40f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [BepInExConfigManager 1.3.0]
[Message:BepInExConfigManager] [UniverseLib] UniverseLib 1.5.1 initializing...
[Message:BepInExConfigManager] [UniverseLib] Finished UniverseLib initial setup.
[Info   :   BepInEx] Loading [HsMod 6.5.2.2]
[Info   :     HsMod] Plugin HsMod is loaded!
[Warning:HsMod.MyLogger] Patcher => Patched 0 methods
[Error  :HsMod.MyLogger] PatchAntiCheat => Could not load type AntiCheatSDK.AntiCheatManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null) 

[Error  :HsMod.MyLogger] HsMod patch failed!
[Warning:HsMod.MyLogger] PatchMisc => Patched 37 methods
[Warning:HsMod.MyLogger] PatchEmote => Patched 5 methods
[Warning:HsMod.MyLogger] PatchIGMMessage => Patched 10 methods
[Warning:HsMod.MyLogger] PatchMercenaries => Patched 1 methods
[Warning:HsMod.MyLogger] PatchHearthstone => Patched 13 methods
[Warning:HsMod.MyLogger] PatchLogArchive => Patched 1 methods
[Warning:HsMod.MyLogger] PatchBattlegrounds => Patched 9 methods
[Warning:HsMod.MyLogger] PatchFavorite => Patched 10 methods
[Warning:HsMod.MyLogger] PatchFakeDevice => Patched 1 methods
[Warning:HsMod.MyLogger] PatchDevOptioins => Patched 2 methods
[Message:   BepInEx] Chainloader startup complete
[Info   :     HsMod] Plugin HsMod is started!
`

Here's the log output of the latest release 6.5.2.2

**Comment by schengx** [comment]
`[Message:   BepInEx] BepInEx 5.4.23.2 - Hearthstone (11/10/2024 05:49:16)
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, MacOS
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInExConfigManager.Mono.Patcher 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2021.3.40f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [BepInExConfigManager 1.3.0]
[Message:BepInExConfigManager] [UniverseLib] UniverseLib 1.5.1 initializing...
[Message:BepInExConfigManager] [UniverseLib] Finished UniverseLib initial setup.
[Info   :   BepInEx] Loading [HsMod 6.5.2.2]
[Info   :     HsMod] Plugin HsMod is loaded!
[Warning:HsMod.MyLogger] Patcher => Patched 0 methods
[Error  :HsMod.MyLogger] PatchAntiCheat => Could not load type AntiCheatSDK.AntiCheatManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null) 

[Error  :HsMod.MyLogger] HsMod patch failed!
[Warning:HsMod.MyLogger] PatchMisc => Patched 37 methods
[Warning:HsMod.MyLogger] PatchEmote => Patched 5 methods
[Warning:HsMod.MyLogger] PatchIGMMessage => Patched 10 methods
[Warning:HsMod.MyLogger] PatchMercenaries => Patched 1 methods
[Warning:HsMod.MyLogger] PatchHearthstone => Patched 13 methods
[Warning:HsMod.MyLogger] PatchLogArchive => Patched 1 methods
[Warning:HsMod.MyLogger] PatchBattlegrounds => Patched 9 methods
[Warning:HsMod.MyLogger] PatchFavorite => Patched 10 methods
[Warning:HsMod.MyLogger] PatchFakeDevice => Patched 1 methods
[Warning:HsMod.MyLogger] PatchDevOptioins => Patched 2 methods
[Message:   BepInEx] Chainloader startup complete
[Info   :     HsMod] Plugin HsMod is started!
`

**Comment by Pik-4** [comment]
> `[Message: BepInEx] BepInEx 5.4.23.2 - Hearthstone (11/10/2024 05:49:16) [Info : BepInEx] Running under Unity vUnknown (post-2017) [Info : BepInEx] CLR runtime version: 4.0.30319.42000 [Info : BepInEx] Supports SRE: True [Info : BepInEx] System platform: Bits64, MacOS [Message: BepInEx] Preloader started [Info : BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2] [Info : BepInEx] Loaded 1 patcher method from [BepInExConfigManager.Mono.Patcher 1.0.0.0] [Info : BepInEx] 2 patcher plugins loaded [Info : BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader] [Message: BepInEx] Preloader finished [Info : BepInEx] Detected Unity version: v2021.3.40f1 [Message: BepInEx] Chainloader ready [Message: BepInEx] Chainloader started [Info : BepInEx] 2 plugins to load [Info : BepInEx] Loading [BepInExConfigManager 1.3.0] [Message:BepInExConfigManager] [UniverseLib] UniverseLib 1.5.1 initializing... [Message:BepInExConfigManager] [UniverseLib] Finished UniverseLib initial setup. [Info : BepInEx] Loading [HsMod 6.5.2.2] [Info : HsMod] Plugin HsMod is loaded! [Warning:HsMod.MyLogger] Patcher => Patched 0 methods [Error :HsMod.MyLogger] PatchAntiCheat => Could not load type AntiCheatSDK.AntiCheatManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
> 
> [Error :HsMod.MyLogger] HsMod patch failed! [Warning:HsMod.MyLogger] PatchMisc => Patched 37 methods [Warning:HsMod.MyLogger] PatchEmote => Patched 5 methods [Warning:HsMod.MyLogger] PatchIGMMessage => Patched 10 methods [Warning:HsMod.MyLogger] PatchMercenaries => Patched 1 methods [Warning:HsMod.MyLogger] PatchHearthstone => Patched 13 methods [Warning:HsMod.MyLogger] PatchLogArchive => Patched 1 methods [Warning:HsMod.MyLogger] PatchBattlegrounds => Patched 9 methods [Warning:HsMod.MyLogger] PatchFavorite => Patched 10 methods [Warning:HsMod.MyLogger] PatchFakeDevice => Patched 1 methods [Warning:HsMod.MyLogger] PatchDevOptioins => Patched 2 methods [Message: BepInEx] Chainloader startup complete [Info : HsMod] Plugin HsMod is started! `

I think it has been loaded normally. Have you configured the correct token?

**Comment by schengx** [comment]
I checked the token many times. But still could you post the website to get the token? I noticed that you deleted all the descriptions and installing steps.

Notably, the game was crushed without any information. As soon as the game starts, the screen goes black, and then it crashes immediately.

**Comment by Pik-4** [comment]
> I checked the token many times. But still could you post the website to get the token? I noticed that you deleted all the descriptions and installing steps.
> 
> Notably, the game was crushed without any information. As soon as the game starts, the screen goes black, and then it crashes immediately.

It's on anothrer branch. Maybe unstripped_corlib is not correct. Well, I don't have a Mac device at the moment, so it may take some time to repair the Mac.

**Comment by schengx** [comment]
I checked the token again and I'm pretty sure that there's no problem with it. I understand how difficult it is to develop without a Mac environment, I will continuously use HsMod on win, thanks for your work :)

**Comment by Pik-4** [comment]
> I checked the token again and I'm pretty sure that there's no problem with it. I understand how difficult it is to develop without a Mac environment, I will continuously use HsMod on win, thanks for your work :)

Try 6.5.2.3. If the problem still persists, please provide `Hearthstone_data\Managed\*.dll`,  especially `Assembly-CSharp.dll`, thanks.

**Comment by feixqemn** [comment]
Hsmod 6.5.3.1 currently works well on BeplnEx 5.4.23.2, Hearthstone 31.0, with a very small difference in the installation steps: change the directory of dll_search_path_override to BepInEx/unstripped_corlib, that is:`dll_search_path_override="BepInEx/unstripped_corlib"`.

# Get the [token](https://www.battlenet.com.cn/login/zh-cn/?app=wtcg) here and copy after http://localhost:0/?ST= and before &accountId=

# Some verify url
https://www.battlenet.com.cn/login/zh-cn/?app=wtcg
https://us.battle.net/login/en/?app=wtcg
https://tw.battle.net/login/zh/?app=wtcg
https://kr.battle.net/login/zh/?app=wtcg
https://eu.battle.net/login/zh/?app=wtcg
...

The url for token of CN server is wrong here. It should be [https://account.battlenet.com.cn/login/zh-cn/?app=wtcg](https://account.battlenet.com.cn/login/zh-cn/?app=wtcg)

**Comment by Pik-4** [comment]
fixed. read new readme.
