### ISSUE TITLE
按f5显示菜单但无实际作用

### ISSUE THREAD

**Issue by 379990064** [Pik-4/HsMod#106]
[Message:   BepInEx] BepInEx 5.4.21.0 - Hearthstone (2024/10/11 11:13:51)
[Info   :   BepInEx] Running under Unity v2021.3.40.7326391
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInExConfigManager.Mono.Patcher 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [BepInExConfigManager 1.3.0]
[Message:BepInExConfigManager] [UniverseLib] UniverseLib 1.5.1 initializing...
[Message:BepInExConfigManager] [UniverseLib] Finished UniverseLib initial setup.
[Info   :   BepInEx] Loading [HsMod 2.4.0.1]
[Info   :     HsMod] Plugin HsMod is loaded!
[Warning:HsMod.MyLogger] Patcher => Patched 0 methods
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Blizzard.BlizzardErrorMobile.ExceptionReporter and name ReportCaughtException and parameters (string, string)
[Error  :HsMod.MyLogger] PatchMisc => Patching exception in method null
[Error  :HsMod.MyLogger] PatchFiresideGathering => Could not load type FiresideGatheringManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
[Warning:HsMod.MyLogger] PatchEmote => Patched 5 methods
[Warning:HsMod.MyLogger] PatchIGMMessage => Patched 7 methods
[Warning:HsMod.MyLogger] PatchMercenaries => Patched 1 methods
[Warning:HsMod.MyLogger] PatchHearthstone => Patched 14 methods
[Warning:  HarmonyX] AccessTools.TypeByName: Could not find type named LogArchive
[Error  :HsMod.MyLogger] PatchLogArchive => Patching exception in method static System.Reflection.MethodInfo HsMod.Patcher+PatchLogArchive::PublicLogArchiveLogPath()
[Warning:HsMod.MyLogger] PatchBattlegrounds => Patched 9 methods
[Error  :HsMod.MyLogger] PatchFavorite => Could not load type CoinManager, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
[Warning:HsMod.MyLogger] PatchFakeDevice => Patched 1 methods
[Warning:HsMod.MyLogger] PatchDevOptioins => Patched 2 methods
[Warning:HsMod.MyLogger] PatchMercenariesReward => Patched 8 methods
[Message:   BepInEx] Chainloader startup complete
[Info   :     HsMod] Plugin HsMod is started!
[Message:BepInExConfigManager] [UniverseLib] Initialized Legacy Input support
[Message:BepInExConfigManager] [UniverseLib] Loaded modern bundle for Unity 2021.3.40f1
[Message:BepInExConfigManager] [UniverseLib] UniverseLib 1.5.1 initialized.
[Warning:HsMod.MyLogger] PatchBoxesReward => Patched 3 methods
[Warning:HsMod.MyLogger] Unpatched PatchBoxesReward!
[Warning:HsMod.MyLogger] Unpatched PatchMercenariesReward!
[Warning:HsMod.MyLogger] PatchBoxesReward => Patched 3 methods
[Warning:HsMod.MyLogger] PatchMercenariesReward => Patched 8 methods
[Warning:HsMod.MyLogger] Unpatched Patcher!
[Warning:HsMod.MyLogger] Unpatched PatchEmote!
[Warning:HsMod.MyLogger] Unpatched PatchIGMMessage!
[Warning:HsMod.MyLogger] Unpatched PatchMercenaries!
[Warning:HsMod.MyLogger] Unpatched PatchHearthstone!
[Warning:HsMod.MyLogger] Unpatched PatchBattlegrounds!
[Warning:HsMod.MyLogger] Unpatched PatchFakeDevice!
[Warning:HsMod.MyLogger] Unpatched PatchDevOptioins!
[Warning:HsMod.MyLogger] Unpatched PatchBoxesReward!
[Warning:HsMod.MyLogger] Unpatched PatchMercenariesReward!

**Comment by 379990064** [comment]
不对 改卡特效有用 但加速齿轮没用

**Comment by Ben-John933** [comment]
连启用都不保存了，启用保存后重开还是关闭状态

**Comment by Pik-4** [comment]
你是怎么找到这么远古版本的？
