### ISSUE TITLE
换肤之后技能不改变的问题 主要是神雷诺影响很大

### ISSUE THREAD

**Issue by alexcellsinetous** [Pik-4/HsMod#107]
其他大多数英雄牌基本都是固定技能,不变化也就图标或者特效没有，影响不是很大,但神雷诺技能随机变化,导致变完后我必须得将皮肤id重置加拔线(dva没人带 但也有影响)， 能不能写个一键拔线加皮肤恢复，对局结束的时候再把之前清除的皮肤id回复就行，或者把雷诺的技能跟这张卡绑定，但估计不好实现

**Comment by 01Vanadium** [comment]
主要是因为这个大螺丝是第一个双职业皮肤，估计逻辑还要区分战士和萨满很麻烦

**Comment by Pik-4** [comment]
rtfm
