### ISSUE TITLE
请问是不是插件最近会导致重连或者崩溃？

### ISSUE THREAD

**Issue by zwxbest** [Pik-4/HsMod#109]
不管玩国服还是外服，经常一局游戏打一半，大约10分钟左右，就卡住然后重连。

有的时候重连也没有，直接单出连接失败的窗口，得关掉重新登录。

期间网络一直是好的，玩游戏的时候看的网页直播也一直没有断。

**Comment by 01Vanadium** [comment]
没有遇到过，我这边很稳定

**Comment by Pik-4** [comment]
重连不至于，卡死倒有可能
