### ISSUE TITLE
金卡无动态特效

### ISSUE THREAD

**Issue by kawakamitomie2** [Pik-4/HsMod#11]

**Comment by kawakamitomie2** [comment]
钻石卡都有特效只有金卡无动态特效

**Comment by kawakamitomie2** [comment]
[HsMod.zip](https://github.com/Pik-4/HsMod/files/9945642/HsMod.zip)

**Comment by Pik-4** [comment]
是所有金卡吗？有一些金卡是没有动态特效的（例如在佣兵）；此外炉石画质是高吗？

**Comment by kawakamitomie2** [comment]
强制的所有金卡都无动态特性,画质是高，佣兵也没有动态特效。

**Comment by Pik-4** [comment]
应该是新版本更新的问题，我尝试研究一下

**Comment by kawakamitomie2** [comment]
好的辛苦了

**Comment by Pik-4** [comment]
已修复，如果还有问题，请重新提交issue
