### ISSUE TITLE
无法打开界面

### ISSUE THREAD

**Issue by messiasama** [Pik-4/HsMod#116]
### Describe your problem./描述你的问题。

按f4显示已开启，但是按f5一点反应没有

**Comment by LoverD321** [comment]
f5好像改完后本来就是打不开的，但是我按照上一个文章修改HsMod.cfg配置文件也没用

**Comment by abevol** [comment]
编写了一个空白游戏用于模拟加载 `HsMod` 和 `BepInExConfigManager`，以对 `HsMod` 的配置文件进行可视化编辑。
（难道我真的是个天才🤣）

注：这只是一个缓解方案，需要一定的动手能力，如想安逸请等待 `HsMod` 作者更新。

## 仓库地址
[HsModConfigEditor]

## 截屏预览

![Preview](https://github.com/abevol/HsModConfigEditor/blob/master/Preview.png?raw=true)

[HsModConfigEditor]: https://github.com/abevol/HsModConfigEditor

**Comment by LoverD321** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'

**Comment by LoverD321** [comment]
> 编写了一个空白游戏用于模拟加载 [HsMod](https://github.com/Pik-4/HsMod) 和 [BepInExConfigManager](https://github.com/sinai-dev/BepInExConfigManager)，以对 [HsMod](https://github.com/Pik-4/HsMod) 的配置文件进行可视化编辑。 （难道我真的是个天才🤣）
> 
> ## 仓库地址
> [HsModConfigEditor](https://github.com/abevol/HsModConfigEditor)
> 
> ## 截屏预览
> ![Preview](https://github.com/abevol/HsModConfigEditor/blob/master/Preview.png?raw=true)

怎么搞啊哥，我小白运行不来

**Comment by messiasama** [comment]
> 编写了一个空白游戏用于模拟加载 和 ，以对 的配置文件进行可视化编辑。 （难道我真的是个天才🤣）`HsMod``BepInExConfigManager``HsMod`
> 
> ## 仓库地址
> [HsModConfig编辑器](https://github.com/abevol/HsModConfigEditor)
> 
> ## 截屏预览
> ![Preview](https://github.com/abevol/HsModConfigEditor/blob/master/Preview.png?raw=true)

大佬nb

**Comment by ssdawesf** [comment]
> 编写了一个空白游戏用于模拟加载 `HsMod` 和 `BepInExConfigManager`，以对 `HsMod` 的配置文件进行可视化编辑。 （难道我真的是个天才🤣）
> 
> ## 仓库地址
> [HsModConfigEditor](https://github.com/abevol/HsModConfigEditor)
> 
> ## 截屏预览
> ![Preview](https://github.com/abevol/HsModConfigEditor/blob/master/Preview.png?raw=true)

真的是天才啊  大佬

**Comment by HuYeoo** [comment]
大佬 寫一下這個編輯器使用步驟可以嗎 感謝感謝🥹

**Comment by LoverD321** [comment]
> 编写了一个空白游戏用于模拟加载 `HsMod` 和 `BepInExConfigManager`，以对 `HsMod` 的配置文件进行可视化编辑。 （难道我真的是个天才🤣）
> 
> 注：这只是一个缓解方案，需要一定的动手能力，如想安逸请等待 `HsMod` 作者更新。
> 
> ## 仓库地址
> [HsModConfigEditor](https://github.com/abevol/HsModConfigEditor)
> 
> ## 截屏预览
> ![Preview](https://github.com/abevol/HsModConfigEditor/blob/master/Preview.png?raw=true)

大佬，怎么把它加载炉石文件里面啊

**Comment by abevol** [comment]
> 大佬，怎么把它加载炉石文件里面啊

将修改后的配置文件 HsMod.cfg 复制到游戏目录下的 BepInEx\config 文件夹内。
或者通过 `mklink` 创建符号链接，可免去手动复制之苦。
命令示例：`mklink "D:\GameTools\HsModConfigEditor\BepInEx\config\HsMod.cfg" "D:\NetGame\Hearthstone\BepInEx\config\HsMod.cfg"`

**Comment by abevol** [comment]
> 大佬 寫一下這個編輯器使用步驟可以嗎 感謝感謝🥹

使用步骤已经在仓库中写明啦，请前往 [HsModConfigEditor] 查看，如果有不理解的地方可以继续提问。

[HsModConfigEditor]: https://github.com/abevol/HsModConfigEditor

**Comment by HuYeoo** [comment]
> 有

好的 感謝

**Comment by Pik-4** [comment]
> 编写了一个空白游戏用于模拟加载 `HsMod` 和 `BepInExConfigManager`，以对 `HsMod` 的配置文件进行可视化编辑。 （难道我真的是个天才🤣）
> 
> 注：这只是一个缓解方案，需要一定的动手能力，如想安逸请等待 `HsMod` 作者更新。
> 
> ## 仓库地址
> [HsModConfigEditor](https://github.com/abevol/HsModConfigEditor)
> 
> ## 截屏预览
> ![Preview](https://github.com/abevol/HsModConfigEditor/blob/master/Preview.png?raw=true)

事实上，你可以研究一下 #114 的最后一条，也就是不建议那条，那玩意的配置其实是可以用的。

**Comment by Pik-4** [comment]
F5已经删了

**Comment by abevol** [comment]
> 事实上，你可以研究一下 #114 的最后一条，也就是不建议那条，那玩意的配置其实是可以用的。

大佬，那玩意我试过了，实在是太丑了🤣
