### ISSUE TITLE
发射星舰时会卡死

### ISSUE THREAD

**Issue by BitAstray** [Pik-4/HsMod#117]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

在炉石竞技场中，可以使用最新版本的卡包。在使用最新版本卡包发射星舰时会卡死。
在昨天，未使用插件时，在乱斗模式中发射星舰未出现此问题

### Logs/日志

[LogOutput.log](https://github.com/user-attachments/files/17583004/LogOutput.log)
[config.zip](https://github.com/user-attachments/files/17583029/config.zip)

### Environment info/环境信息

- OS Platform/操作系统:windows10
- HsMod Version/HsMod版本:7.0
- BepInEx Version/BepInEx版本:5.32
- Hearthstone Version/炉石版本: 31.0.0
- Unity(unstripped_corlib) Version/Unity(unstripped_corlib)版本:

**Comment by Pik-4** [comment]
日志中并无报错，周末我再看看

**Comment by BitAstray** [comment]
好的，辛苦了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月31日 14:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Pik-4/HsMod] 发射星舰是会卡死 (Issue #117) |

日志中并无报错，周末我再看看

**Comment by Mrsun2022** [comment]
这是游戏bug,不是hsmod的问题，我手机玩 也会掉线

**Comment by BitAstray** [comment]
> 这是游戏bug,不是hsmod的问题，我手机玩 也会掉线

我每次发射都卡死，

**Comment by hupanxiaozhu** [comment]
> > 这是游戏bug，不是hsmod的问题，我手机玩 也会掉线
> 
> 我每次发射都卡死，

人家都说了是游戏BUG，麻烦先去排查一下，起码把插件删除干净再看看能不能复现。或者去相关的炉石游戏论坛看看BUG反馈

**Comment by Pik-4** [comment]
暂未发现掉线，疑似炉石bug
