### ISSUE TITLE
金卡功能无效，日志提示 Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound

### ISSUE THREAD

**Issue by TYZRPVX** [Pik-4/HsMod#118]
Fixed

**Comment by TYZRPVX** [comment]
```
# General options for Unity Doorstop
[General]

# Enable Doorstop?
enabled = true

# Path to the assembly to load and execute
# NOTE: The entrypoint must be of format `static void Doorstop.Entrypoint.Start()`
target_assembly=BepInEx\core\BepInEx.Preloader.dll

# If true, Unity's output log is redirected to <current folder>\output_log.txt
redirect_output_log = false

# Overrides the default boot.config file path
boot_config_override =

# If enabled, DOORSTOP_DISABLE env var value is ignored
# USE THIS ONLY WHEN ASKED TO OR YOU KNOW WHAT THIS MEANS
ignore_disable_switch = false

# Options specific to running under Unity Mono runtime
[UnityMono]

# Overrides default Mono DLL search path
# Sometimes it is needed to instruct Mono to seek its assemblies from a different path
# (e.g. mscorlib is stripped in original game)
# This option causes Mono to seek mscorlib and core libraries from a different folder before Managed
# Original Managed folder is added as a secondary folder in the search path
# To specify multiple paths, separate them with semicolons (;)
dll_search_path_override = BepInEx\unstripped_corlib

# If true, Mono debugger server will be enabled
debug_enabled = false

# When debug_enabled is true, specifies the address to use for the debugger server
debug_address = 127.0.0.1:10000

# If true and debug_enabled is true, Mono debugger server will suspend the game execution until a debugger is attached
debug_suspend = **false**
```

**Comment by GeekGeniusSheldon** [comment]
> ### Please check before submitting an issue/提交问题前请检查
> * [x]  I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
> * [x]  I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
> * [x]  I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备
> 
> ### Describe the bug/描述你的问题。
> ```
> [Info   : Unity Log] RegisterScreenBox tempGuardianVars=NetCache+NetCacheFeatures
> [Warning: Unity Log] Couldn't find Favorite Hero for hero class: DEMONHUNTER defaulting to Vanilla Hero!
> [Error  : Unity Log] Releasing render texture that is set as Camera.targetTexture!
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Warning: Unity Log] LoadHeroButtonsForFavoriteHeroes: CCouldn't find Favorite Hero for hero class: DEMONHUNTER defaulting to Vanilla Hero!
> [Warning: Unity Log] LoadHeroButtonsForFavoriteHeroes: CCouldn't find Favorite Hero for hero class: DEMONHUNTER defaulting to Vanilla Hero!
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Warning: Unity Log] Couldn't find Favorite Hero for hero class: DEMONHUNTER defaulting to Vanilla Hero!
> [Info   : Unity Log] No subsequent reward found for Hero Class: DEATHKNIGHT after Level: 5. Check FIXED REWARD MAPS if you think there should be one
> [Info   : Unity Log] No subsequent reward found for Hero Class: DEMONHUNTER after Level: 7. Check FIXED REWARD MAPS if you think there should be one
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Info   : Unity Log] [GameNetLogger] GameMgr.ChangeFindGameState() - state: CLIENT_STARTED, previous state: INVALID
> [Info   : Unity Log] [GameNetLogger] GameMgr.DoDefaultFindGameEventBehavior() -  FindGameEventData: CLIENT_STARTED
> [Info   : Unity Log] [GameNetLogger] GameMgr.OnGameQueueEvent() - QueueEvent: QUEUE_DELAY
> [Info   : Unity Log] [GameNetLogger] GameMgr.ChangeFindGameState() - state: BNET_QUEUE_DELAYED, previous state: CLIENT_STARTED
> [Info   : Unity Log] [GameNetLogger] GameMgr.DoDefaultFindGameEventBehavior() -  FindGameEventData: BNET_QUEUE_DELAYED
> [Info   : Unity Log] [GameNetLogger] GameMgr.OnGameQueueEvent() - QueueEvent: QUEUE_GAME_STARTED
> [Info   : Unity Log] [GameNetLogger] GameMgr.ChangeFindGameState() - state: SERVER_GAME_CONNECTING, previous state: BNET_QUEUE_DELAYED
> [Info   : Unity Log] [GameNetLogger] GameMgr.DoDefaultFindGameEventBehavior() -  FindGameEventData: SERVER_GAME_CONNECTING
> [Info   : Unity Log] [GameNetLogger] Network.GotoGameServe() - gameConnectionDisconnected True, IsRestoringGameState: False
> [Info   : Unity Log] [GameNetLogger] Network.GotoGameServe() - address= 47.97.20.226:3724, game=70667, client=86755785, spectateKey=feafbc reconnecting=False
> [Info   : Unity Log] TcpConnection - possible ip address: 47.97.20.226
> [Info   : Unity Log] [GameNetLogger] RpcController - Trying to connect to 47.97.20.226
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Info   : Unity Log] [GameNetLogger] Network.OnGameServerConnectEvent() - Connecting to game server with error code ERROR_OK
> [Info   : Unity Log] [GameNetLogger] Network.SendGameServerHandshake()
> [Info   : Unity Log] [GameNetLogger] GameMgr.OnGameSetup()
> [Info   : Unity Log] [GameNetLogger] GameMgr.ChangeFindGameState() - state: SERVER_GAME_STARTED, previous state: SERVER_GAME_CONNECTING
> [Info   : Unity Log] [GameNetLogger] GameMgr.DoDefaultFindGameEventBehavior() -  FindGameEventData: SERVER_GAME_STARTED
> [Info   : Unity Log] SERVER_GAME_STARTED event - Loading Gameplay Scene
> [Info   : Unity Log] [GameNetLogger] GameMgr.DoDefaultFindGameEventBehavior() - SERVER_GAME_STARTED event - Loading Gameplay Scene
> [Info   : Unity Log] [GameNetLogger] 
> [Info   : Unity Log] [GameNetLogger] GameMgr.ChangeFindGameState() - state: INVALID, previous state: SERVER_GAME_STARTED
> [Info   : Unity Log] [GameNetLogger] GameMgr.DoDefaultFindGameEventBehavior() -  FindGameEventData: INVALID
> [Info   : Unity Log] Gameplay.Awake() - CurrentMode=GAMEPLAY, PrevMode=ADVENTURE
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Asset 'HERO_09d_HeroTray_golden.tif:e584a1a0c6513ea4087c37ccaaa7dd4b' is missing from asset bundles
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] HistoryEntry.GetSourceInfo() - no source info
> [Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: D:/Games/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
> [Warning:HsMod.MyLogger] HsMod Languages: zhCN
> [Warning:HsMod.MyLogger] HsMod Languages: zhCN
> ```
> 
> ### To Reproduce/如何复现
> _No response_
> 
> ### Expected behavior/期望结果
> _No response_
> 
> ### Screenshots/截图
> _No response_
> 
> ### Logs/日志
> _No response_
> 
> ### Environment info/环境信息
> * OS Platform/操作系统:
> * HsMod Version/HsMod版本: latest
> * BepInEx Version/BepInEx版本: BepInEx 5.4.23.2
> * Hearthstone Version/炉石版本: latest
> * Unity(unstripped_corlib) Version/Unity(unstripped_corlib)版本: latest
> 
> ### Additional context/其他信息
> _No response_

我的完全没问题

**Comment by Pik-4** [comment]
> ```
> # General options for Unity Doorstop
> [General]
> 
> # Enable Doorstop?
> enabled = true
> 
> # Path to the assembly to load and execute
> # NOTE: The entrypoint must be of format `static void Doorstop.Entrypoint.Start()`
> target_assembly=BepInEx\core\BepInEx.Preloader.dll
> 
> # If true, Unity's output log is redirected to <current folder>\output_log.txt
> redirect_output_log = false
> 
> # Overrides the default boot.config file path
> boot_config_override =
> 
> # If enabled, DOORSTOP_DISABLE env var value is ignored
> # USE THIS ONLY WHEN ASKED TO OR YOU KNOW WHAT THIS MEANS
> ignore_disable_switch = false
> 
> # Options specific to running under Unity Mono runtime
> [UnityMono]
> 
> # Overrides default Mono DLL search path
> # Sometimes it is needed to instruct Mono to seek its assemblies from a different path
> # (e.g. mscorlib is stripped in original game)
> # This option causes Mono to seek mscorlib and core libraries from a different folder before Managed
> # Original Managed folder is added as a secondary folder in the search path
> # To specify multiple paths, separate them with semicolons (;)
> dll_search_path_override = BepInEx\unstripped_corlib
> 
> # If true, Mono debugger server will be enabled
> debug_enabled = false
> 
> # When debug_enabled is true, specifies the address to use for the debugger server
> debug_address = 127.0.0.1:10000
> 
> # If true and debug_enabled is true, Mono debugger server will suspend the game execution until a debugger is attached
> debug_suspend = **false**
> ```

配置提供错误
