### ISSUE TITLE
新版本安装mod后，火石记牌器提示内存错误

### ISSUE THREAD

**Issue by peil1ng** [Pik-4/HsMod#119]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

如题，请问是个例嘛？

### Environment info/环境信息

- OS Platform/操作系统:
- HsMod Version/HsMod版本:
- BepInEx Version/BepInEx版本:
- Hearthstone Version/炉石版本:
- Unity(unstripped_corlib) Version/Unity(unstripped_corlib)版本:

**Comment by lomk-pig** [comment]
我这没问题，唯一的问题就是ctrl +D快速重连失效了

**Comment by peil1ng** [comment]
删了重下，重新安装，依然有内存读取错误，不懂为什么会这样，更新之前没有遇到类似情况。。。

**Comment by httpsColon** [comment]
没遇到啊

**Comment by wexiao17** [comment]
内存错误我以前碰到过，可以试着退出overwolf并已管理员运行火石，虽然我更新后没试过天梯，但我目前战旗没有问题
