### ISSUE TITLE
[Custom]大佬您好，进入炉石后按F4显示插件正在运行但是F5没有反应，酒馆方面没有感受到加速和其他优化（依照最新的安装教程安装的），可能是我对这个插件毫无理解，麻烦您了

### ISSUE THREAD

**Issue by Sumuqiu32** [Pik-4/HsMod#123]
### Describe your problem./描述你的问题。

大佬您好，进入炉石后按F4显示插件正在运行但是F5没有反应，酒馆方面没有感受到加速和其他优化（依照最新的安装教程安装的），可能是我对这个插件毫无理解，麻烦您了

**Comment by Sumuqiu32** [comment]
已经解决！是因为我没有找到正确的配置文件，我个人学习到的是：应该在Hearthstone\BepInEx\config中找到HsMod.cfg用txt打开修改配置。麻烦了！，希望能对之后没有了解过的大佬们有用

**Comment by httpsColon** [comment]
缓解方案你那能用吗，为啥我进不去游戏

**Comment by Sumuqiu32** [comment]
> 缓解方案你那能用吗，为啥我进不去游戏

你把这个文件删了试试？client.config，这个越过战网直接打开炉石的文件，我之前开了这个也一直卡在门前
