### ISSUE TITLE
换肤功能无法读取到皮肤信息

### ISSUE THREAD

**Issue by JenseYoung** [Pik-4/HsMod#126]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [ ] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

作者你好，我仔细读了读手册，目前自身的换肤功能中出现了一些问题。
不知道是否与我的设备有关，我在我的设备1中是正常可以运行的，但是在设备2中无法使用。
我目前知道有两个换肤功能，一个是修改HsMod.cfg中的英雄配置，但这个功能无法更换英雄技能我并没有使用。
第二个换肤功能在我的设备2中，我按下F4显示插件正在运行，但是并无HsSkins.log文件生成，生成了HsSkins.cfg文件，但HsSkins.cfg的换肤功能也无法正常使用。我确认自身输入的换肤配置没有错误，不知能否帮我看下Log日志，麻烦了。

### To Reproduce/如何复现

None

### Expected behavior/期望结果

<img width="960" alt="6a38dfa2b04361dc69d02883d13aeba" src="https://github.com/user-attachments/assets/15c1f018-371c-4e76-a455-4d57e8c13fe6">

### Screenshots/截图

![3bed190c8d3467c0f57c662fd4ea321](https://github.com/user-attachments/assets/f9e3096d-3202-4d11-8721-e59d57f53584)

### Logs/日志

[LogOutput.log](https://github.com/user-attachments/files/17613747/LogOutput.log)

**Comment by Pik-4** [comment]
建议开启炉石后，从[web](http://127.0.0.1:58744)查看

**Comment by JenseYoung** [comment]
[Uploading HsSkins.cfg…]()

**Comment by JenseYoung** [comment]
> 建议开启炉石后，从[web](http://127.0.0.1:58744)查看

感谢，点开web的皮肤信息生成了HsSkins.log。
但是我每次新加皮肤删除后重新生成HsSkins.cfg，再配置发现换肤功能正常了。
如果直接修改HsSkins.cfg的内容并F4有时候换肤功能失败，不知是什么原因。
感觉直接修改并F4不是很灵敏，两者的信息是一样的。
有点奇怪了，待等大哥F5后续更新也不用那么麻烦了。
