### ISSUE TITLE
大佬您好，按照最新教程安装后F4和F5都完全没反应

### ISSUE THREAD

**Issue by madsweater** [Pik-4/HsMod#127]
### Describe your problem./描述你的问题。

其实这个问题困扰我很久了。去年的时候我在一个炉石群里下载了一个佣兵插件，这个插件借用了您的hsmod，然后那个作者是把调用面板的快捷键改成了F1，启用/停止运行插件改为F9。之后因为炉石更新，hsmod也更新，我删掉了他的插件之后，按照之前的《更为清晰明了的安装教程》安装，进游戏后F5依然调用不出插件，于是我把老的佣兵插件先装回去，然后再用您更新的hsmod文件去替换同名文件，进去之后F1依然可以调出您的插件。直到国服开服之后，就完全不可行了。昨天我也卸载了炉石和战网，全部重装然后F5还是没用，Bepinex下面就没有自动生成config，请问有什么办法吗？ 如果能帮忙看看的话感激不尽！ 
<img width="632" alt="Snipaste_2024-11-04_08-57-41" src="https://github.com/user-attachments/assets/750bc4a8-cd70-4cff-b981-a9998510e909">
<img width="593" alt="Snipaste_2024-11-04_08-58-08" src="https://github.com/user-attachments/assets/78d51a1d-6d27-4842-b353-ad3c2f379e69">
<img width="655" alt="Snipaste_2024-11-04_08-58-37" src="https://github.com/user-attachments/assets/715b8595-cbe9-4897-b5fc-82242bdcb802">
<img width="661" alt="Snipaste_2024-11-04_08-58-43" src="https://github.com/user-attachments/assets/53f94935-f627-42d0-9889-635cbc5e3d92">
<img width="707" alt="Snipaste_2024-11-04_08-58-48" src="https://github.com/user-attachments/assets/0a87527f-1dbd-4cc9-a9fa-64fb6f67fbf7">

**Comment by httpsColon** [comment]
首先f5是过去式了，插件管理器暂时用不了，临时解决方案是自己改hsmod.cfg或是换成网页端http://[127.0.0.1:58744/config/index.html] 来管理配置，另外你第二张图应该是dll_search_path_override = BepInEx\unstripped_corlib
