### ISSUE TITLE
cfg无法正常生成

### ISSUE THREAD

**Issue by defidead** [Pik-4/HsMod#128]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

重新安装炉石传说和hsmod无法自动生成hsmod.cfg

### Logs/日志

[Message:   BepInEx] BepInEx 5.4.23.2 - Hearthstone (2024/11/5 10:40:55)
[Info   :   BepInEx] Running under Unity v2021.3.40.7326391
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [HsMod 7.0.1.3]
[Warning:HsMod.MyLogger] C:\Program Files (x86)\Hearthstone\BepInEx\config\BepInEx.cfg: Logging.Unity.LogLevels not found.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HsMod.LocalizationManager.GetCurrentLang () (at <096cdc40689747d090ce956b2837a262>:0)
HsMod.PluginConfig.ConfigBind (BepInEx.Configuration.ConfigFile config) (at <096cdc40689747d090ce956b2837a262>:0)
HsMod.Plugin.Awake () (at <096cdc40689747d090ce956b2837a262>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
Log:get_LogsPath()
Log:BuildRuntimeLogConfig()
Log:Initialize()
Log:GetLoggerFromSystem(String)
Log:get_MobileCallback()
PushNotificationManager:Initialize()

[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Application paused: False
[Warning: Unity Log] Vars retrieved without initialization!
[Info   : Unity Log] Tracert: failed to add ICMP rule.
[Error  : Unity Log] Failed to load config file: 
[Info   : Unity Log] Current working dir=C:\Program Files (x86)\Hearthstone
[Info   : Unity Log] SetLocale: zhCN
[Info   : Unity Log] [Jobs Fallback logger]: [JobQueue.QueueJob] Job (DeeplinkService.PostFullLoginJobs(ID:1)) QUEUED
[Info   : Unity Log] [Jobs Fallback logger]: [JobQueue.QueueJob] Dependency (WaitForFullLoginFlowComplete) added for queued job (DeeplinkService.PostFullLoginJobs(ID:1))
[Info   : Unity Log] [ExceptionReporter] Version 1.1.3
[Info   : Unity Log] [ExceptionReporter] ScreenshotPath: C:/Users/user/AppData/Local/Blizzard/Hearthstone/Exceptions\Screenshot-ljMdeIj93Ag.png
[Info   : Unity Log] [ExceptionReporter] Trying to clean up the old screenshot files.
[Info   : Unity Log] [ExceptionReporter] Loaded exception data from 'C:/Users/user/AppData/Local/Blizzard/Hearthstone/Exceptions/ExceptionReporter.json'
[Info   : Unity Log] [ExceptionReporter] User UUID: e8015a8dc829aa634a42589793e88bb373cc9480
[Info   : Unity Log] Command Line: -launch -uid hs_beta
[Info   : Unity Log] Main thread: True
[Error  : Unity Log] [Asset] Failed to open bundle essential_base_enus-content-0.unity3d. File does not exist: C:/Program Files (x86)/Hearthstone/Data/Win/essential_base_enus-content-0.unity3d|NotFound
[Info   : Unity Log] System Info:
[Info   : Unity Log] SystemInfo - Device Name: 
[Info   : Unity Log] SystemInfo - Device Model: 
[Info   : Unity Log] SystemInfo - OS: Windows 10  (10.0.19045) 64bit
[Info   : Unity Log] SystemInfo - CPU Type: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
[Info   : Unity Log] SystemInfo - CPU Cores: 12
[Info   : Unity Log] SystemInfo - System Memory: 16021
[Info   : Unity Log] SystemInfo - Screen Resolution: 1920x1080
[Info   : Unity Log] SystemInfo - Screen DPI: 96
[Info   : Unity Log] SystemInfo - GPU ID: 9504
[Info   : Unity Log] SystemInfo - GPU Name: NVIDIA GeForce RTX 3060 Laptop GPU
[Info   : Unity Log] SystemInfo - GPU Vendor: NVIDIA
[Info   : Unity Log] SystemInfo - GPU Memory: 3072
[Info   : Unity Log] SystemInfo - GPU Shader Level: 50
[Info   : Unity Log] SystemInfo - GPU NPOT Support: Full
[Info   : Unity Log] SystemInfo - Graphics API (version): Direct3D 11.0 [level 11.1]
[Info   : Unity Log] SystemInfo - Graphics API (type): Direct3D11
[Info   : Unity Log] SystemInfo - Graphics Supported Render Target Count: 8
[Info   : Unity Log] SystemInfo - Graphics Supports 3D Textures: True
[Info   : Unity Log] SystemInfo - Graphics Supports Compute Shaders: True
[Info   : Unity Log] SystemInfo - Graphics Supports Shadows: True
[Info   : Unity Log] SystemInfo - Graphics Supports Sparse Textures: True
[Info   : Unity Log] SystemInfo - Graphics RenderTextureFormat.ARGBHalf: True
[Info   : Unity Log] SystemInfo - Graphics Metal Support: False
[Info   : Unity Log] [ExceptionReporter] Checking the exceptions from previous launch.
[Info   : Unity Log] [ExceptionReporter] Saved exception data(Count: 0) to 'C:/Users/user/AppData/Local/Blizzard/Hearthstone/Exceptions/ExceptionReporter.json'
[Error  : Unity Log] [Asset] Updating ref count from bundle that's not currently open: essential_base_enus-content-0.unity3d|NotFound
[Info   : Unity Log] [Startup] Startup stage Start

### Additional context/其他信息

删除cfg重新自动生成的如下
## Plugin GUID: HsMod

[HsMod]

## (!!! DON'T EDIT IT, unless you know what you are doing) HsMod Init Language
# Setting type: String
# Default value: UNKNOWN
HsMod.Init.Language = UNKNOWN

**Comment by Pik-4** [comment]
fix on https://github.com/Pik-4/HsMod/commit/6ace1672de0aede0f20e16c93e54924c60a4d2c9
