### ISSUE TITLE
配置管理工具需要解压在Hearthstone\BepInEx\HsMod\config，config文件夹是需要手动创建的

### ISSUE THREAD

**Issue by 01Vanadium** [Pik-4/HsMod#129]
### Describe your problem./描述你的问题。

HsModConfigManager.7z

**Comment by 01Vanadium** [comment]
http://127.0.0.1:58744/

**Comment by 01Vanadium** [comment]
https://github.com/Pik-4/HsMod/discussions/122#discussion-7411884

**Comment by 01Vanadium** [comment]
web

**Comment by 01Vanadium** [comment]
[web](url)

**Comment by 01Vanadium** [comment]
[web](http://127.0.0.1:58744/)

**Comment by 01Vanadium** [comment]
电脑铸币完全不懂，直接打开解压的html文件想修改参数但是数据总是显示未连接。。。幸而在问答里找到了作者大大发的web链接，idea里的`0.0.0.0:58744`也能指向修改网站

**Comment by freechao123** [comment]
> 电脑铸币完全不懂，直接打开解压的html文件想修改参数但是数据总是显示未连接。。。幸而在问答里找到了作者大大发的web链接，idea里的`0.0.0.0:58744`也能指向修改网站

其他都没问题，配置修改不显示是什么情况

**Comment by 01Vanadium** [comment]
> > 电脑铸币完全不懂，直接打开解压的html文件想修改参数但是数据总是显示未连接。。。幸而在问答里找到了作者大大发的web链接，idea里的`0.0.0.0:58744`也能指向修改网站
> 
> 其他都没问题，配置修改不显示是什么情况

要打开炉石之后再打开web

**Comment by tuyile-icu** [comment]
你好，配置管理工具在哪里，我的web配置修改页面是白的，其他页面正常

**Comment by jiangLOKI1996** [comment]
> http://127.0.0.1:58744/

Thank！

**Comment by tuyile-icu** [comment]
> > http://127.0.0.1:58744/
> 
> Thank！
这个我知道，就是http://[127.0.0.1:58744/config/index.html](http://127.0.0.1:58744/config/index.html)这里是空白的，其他页面正常，哪里的问题谢谢

**Comment by saiveen1** [comment]
> > > http://127.0.0.1:58744/
> > 
> > 
> > Thank！
> > 这个我知道，就是http://[127.0.0.1:58744/config/index.html](http://127.0.0.1:58744/config/index.html)这里是空白的，其他页面正常，哪里的问题谢谢

[配置管理工具需要解压在Hearthstone\BepInEx\HsMod\config](https://github.com/kanshufan-1107/HsModConfigManager/releases/tag/1.1)
