### ISSUE TITLE
mod配置页面更新数据显示 数据更新失败

### ISSUE THREAD

**Issue by liucheng12156** [Pik-4/HsMod#130]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

mod配置页面更新数据显示 数据更新失败

### Screenshots/截图

![image](https://github.com/user-attachments/assets/ff75a41e-58e9-42d8-8197-14088d87514d)

**Comment by tuyile-icu** [comment]
你好，配置管理工具在哪里，我的web配置修改页面是白的，没有这个

**Comment by httpsColon** [comment]
看看日志，是不是把你的系统识别成了英文的，导致配置文件里没有英雄的key和 value

**Comment by kawakamitomie2** [comment]
> 看看日志，是不是把你的系统识别成了英文的，导致配置文件里没有英雄的key和 value

怎么解决呢

**Comment by httpsColon** [comment]
> > 看看日志，是不是把你的系统识别成了英文的，导致配置文件里没有英雄的key和 value
> 
> 怎么解决呢

替换一个正常的config文件
