### ISSUE TITLE
打开金卡特效后在发射星舰时会卡住

### ISSUE THREAD

**Issue by LDYCC-BLIP** [Pik-4/HsMod#131]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

打开金卡特效后在发射星舰时不会显示星舰的攻击力和生命值，并且画面会卡住，关闭金卡特效或删除mod后在使用相同星舰组件发射星舰均没有出现同样问题

### To Reproduce/如何复现

1.打开mod金卡特效
2.发射星舰

### Expected behavior/期望结果

画面会卡住并且星舰攻击力和生命中均不会显示

### Screenshots/截图

<img width="1120" alt="屏幕截图 2024-11-06 020537" src="https://github.com/user-attachments/assets/00cc8892-cddd-417f-bfce-0416069f27cd">

### Logs/日志

[LogOutput.log](https://github.com/user-attachments/files/17636849/LogOutput.log)

**Comment by ZQY-Joker** [comment]
一样，需要重新拔线

**Comment by peterpanzj** [comment]
这个确实是bug

**Comment by Pik-4** [comment]
能否提供一个测试卡组

**Comment by 97zhouhong** [comment]
更新的文件应该放在哪个文件夹
