### ISSUE TITLE
炉石传说摁F4提示插件状态运行，但是没有设置页面

### ISSUE THREAD

**Issue by laujoe** [Pik-4/HsMod#133]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [ ] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

很感谢开发者，一直在使用。今天更新，按照教程重装之后发现摁F4「提示[91]插件状态：运行」（6.5.3.1，改为7016提示[95]插件状态：运行），而不是像之前有一个设置页面，可以自己调加速和各种设置等。我查询说明，似乎没有发现相关提示，所以在issue询问。如有打扰，还望谅解。

**Comment by laujoe** [comment]
可以在bepinex里的hsmod.cfg调整，能够使用。但是没有页面，所以不清楚是为什么。

**Comment by Pik-4** [comment]
Duplicate #114
