### ISSUE TITLE
[Custom]我按照教程安装了，但是寻找不到hsmod.dll

### ISSUE THREAD

**Issue by duyueovo** [Pik-4/HsMod#135]
### Describe your problem./描述你的问题。

我无法找到完全一致的同名文件将其置入文件夹中，请问是直接将整个Hsmod文件夹中的内容直接置入对应文件么。
我留意到从github下载下来的新包有多个文件，是仅仅需要一个文件夹中的全部dll内容cv到游戏根目录下吗？

**Comment by duyueovo** [comment]
过程卡在了最后一步

**Comment by sudaqi345** [comment]
我也是这样
