### ISSUE TITLE
如何在hsskin.cfg中同时配置多个皮肤映射

### ISSUE THREAD

**Issue by DarkSissi** [Pik-4/HsMod#136]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

我在HsSkin.cfg中同时配置了幸运币和多个皮肤的映射，但是会无限卡加载，目前已经得知是cfg配置问题，但是不知道如何配置可以直接同时配置多个不同对象的映射，求助

### Expected behavior/期望结果

在HsSkin.cfg中直接配置多个对象的映射

### Logs/日志

[HsMod.txt](https://github.com/user-attachments/files/17656401/HsMod.txt)
[LogOutput.log](https://github.com/user-attachments/files/17656387/LogOutput.log)
[HsSkins.txt](https://github.com/user-attachments/files/17656396/HsSkins.txt)

**Comment by Pik-4** [comment]
hsskin目前只支持“英雄”皮肤映射，其他暂不支持，结尾不需要分号。
