### ISSUE TITLE
网页控制背景图片问题

### ISSUE THREAD

**Issue by ssdawesf** [Pik-4/HsMod#143]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

大佬，网页控制的背景都是色图  不过这个也没啥  但是有的色图上面有广告啊
![QQ浏览器截图20241112110825](https://github.com/user-attachments/assets/eae6ddc1-46de-4d79-b0c6-3740ec7cf0d6)

### Describe the solution you'd like/描述你想要的解决方案

能设置自定义背景

**Comment by Pik-4** [comment]
设置能改啊

**Comment by ssdawesf** [comment]
不好意思大佬  但是我没看到修改的地方 怎么修改啊

**Comment by ioi301** [comment]
那个设置里面-背景-参数是http://xxxx.php那个，随便输入个0呀1呀啥的就行了

**Comment by ssdawesf** [comment]
> 那个设置里面-背景-参数是[http://xxxx.php那个,随便输入个0呀一呀啥的就行了](http://xxxx.php%E9%82%A3%E4%B8%AA%EF%BC%8C%E9%9A%8F%E4%BE%BF%E8%BE%93%E5%85%A5%E4%B8%AA0%E5%91%801%E5%91%80%E5%95%A5%E7%9A%84%E5%B0%B1%E8%A1%8C%E4%BA%86)

好的 感谢  没看到

**Comment by httpsColon** [comment]
x账户停用了啊，这网页控制台能修改hsmod.cfg了吗
