### ISSUE TITLE
HsMod 似乎不兼容 HSTtracker 记牌器

### ISSUE THREAD

**Issue by leonlee0506** [Pik-4/HsMod#144]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

我使用macos 可以完美运行mod。但是HSTracker https://github.com/HearthSim/HSTracker 不显示记牌器。 我猜测是因为 HSTracker 通过 从`/Applications/Hearthstone/Logs` 读取logs。 但是如果 我们开始炉石 从命令行， log 的生成 获取和正常启动炉石 不一样。 感谢！

**Comment by Pik-4** [comment]
我不用hdt，建议自行分析HSTracker源码。

**Comment by iamyou** [comment]
分析了一下，如果是用命令行启动，Deck.log等日志会丢失，原因不明，如果能修复这个可能可以顺带修复视障插件。

**Comment by freechao123** [comment]
> 分析了一下，如果是用命令行启动，Deck.log等日志会丢失，原因不明，如果能修复这个可能可以顺带修复视障插件。

有解决办法了吗
