### ISSUE TITLE
无法使用插件

### ISSUE THREAD

**Issue by OceanZen9** [Pik-4/HsMod#148]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [ ] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

按照README多次安装，查阅之前的issue修改HsSkins.cfg，但是进入游戏却没有反应，同时Hearthstone\BepInEx\HsMod文件夹为空

### To Reproduce/如何复现

-1.按照按照README安装
-2.修改HsSkins.cfg
-3.启动游戏

### Expected behavior/期望结果

支持炉石自动金卡、钻石卡

### Logs/日志

[LogOutput.log](https://github.com/user-attachments/files/17893948/LogOutput.log)
[HsMod.txt](https://github.com/user-attachments/files/17893996/HsMod.txt)
[HsSkins.txt](https://github.com/user-attachments/files/17893997/HsSkins.txt)

**Comment by IuckinCoffee** [comment]
b站搜索hsmod 有windows平台教程

**Comment by Pik-4** [comment]
Duplicate. #136
