### ISSUE TITLE
更新以后F5打不开面板是什么情况啊

### ISSUE THREAD

**Issue by zwx0502** [Pik-4/HsMod#153]
### Describe your problem./描述你的问题。

重新装了一遍以后再进游戏好像打不开面板了

**Comment by httpsColon** [comment]
f5不是早就不能用了吗

**Comment by zwx0502** [comment]
> f5不是早就不能用了吗

好久没上了，啥也不知道，求大佬教教现在怎么设置啊

**Comment by infseers** [comment]
> > f5不是早就不能用了吗
> 
> 好久没上了，啥也不知道，求大佬教教现在怎么设置啊

现在改用网页端了http://127.0.0.1:58744/

**Comment by Huangjiaming95** [comment]
> > > f5不是早就不能用了吗
> > 
> > 
> > 好久没上了，啥也不知道，求大佬教教现在怎么设置啊
> 
> 现在改用网页端了http://127.0.0.1:58744/

大佬现在怎么设置呀

**Comment by zwx0502** [comment]
感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月05日 16:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Pik-4/HsMod] 更新以后F5打不开面板是什么情况啊 (Issue #153) |

f5不是早就不能用了吗

好久没上了，啥也不知道，求大佬教教现在怎么设置啊

现在改用网页端了http://127.0.0.1:58744/

大佬现在怎么设置呀

**Comment by Huangjiaming95** [comment]
> 感谢
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年12月05日 16:12 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [Pik-4/HsMod] 更新以后F5打不开面板是什么情况啊 (Issue #153) | f5不是早就不能用了吗 好久没上了，啥也不知道，求大佬教教现在怎么设置啊 现在改用网页端了http://127.0.0.1:58744/ 大佬现在怎么设置呀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

你会设置了吗

**Comment by zwx0502** [comment]
说实话不太清楚😢还没试过，登上这个网址就行了吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月05日 16:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Pik-4/HsMod] 更新以后F5打不开面板是什么情况啊 (Issue #153) |

感谢
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年12月05日 16:12 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [Pik-4/HsMod] 更新以后F5打不开面板是什么情况啊 (Issue #153) | f5不是早就不能用了吗 好久没上了，啥也不知道，求大佬教教现在怎么设置啊 现在改用网页端了http://127.0.0.1:58744/ 大佬现在怎么设置呀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

你会设置了吗
