### ISSUE TITLE
关于一些mac使用上的问题

### ISSUE THREAD

**Issue by onns** [Pik-4/HsMod#16]
其实mac我还没能成功换皮 所以wiki可能会缺失部分内容 所以想问问配置要如何生效
文件分隔符今天看起来还是失败的
不知道会不会和这个有关系 我是在skin.cfg里配置了id映射 但是没成功

**Comment by Pik-4** [comment]
还是不能在`Hearthstone/BepInEx/config`目录下创建HsSkins.cfg嘛，理论上我在2.1.1.1版本的时候就已经修复过`\`的问题了。
关于是否成功替换，目前没做提示，理论上在运行炉石后自动创建的HsSkins.cfg，添加映射`xxxx:xxxx`之后，再按下F4（或重启炉石），会立即生效。

**Comment by onns** [comment]
ok了，并且m1测试也没问题，inter的我也试了
<img width="1920" alt="Snipaste_2022-12-12_01-30-36" src="https://user-images.githubusercontent.com/16622934/206919219-385d12a9-4490-4faa-84bd-f22199ffd726.png">
