### ISSUE TITLE
网页配置打开白屏

### ISSUE THREAD

**Issue by Stardustll** [Pik-4/HsMod#164]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [X] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

网页配置打开白屏，其他网页选项正常，能正常查看信息

### Expected behavior/期望结果

能够通过网页修改配置，而不是更改配置文件

### Screenshots/截图

![image](https://github.com/user-attachments/assets/f1b5299a-c470-48bd-93b0-ac7a801a7daa)

### Logs/日志

[LogOutput.log](https://github.com/user-attachments/files/18057351/LogOutput.log)

**Comment by kawakamitomie2** [comment]
一样 我也是打开以后什么也没有

**Comment by bailan999** [comment]
解决了吗 怎么解决的

**Comment by Stardustll** [comment]
已解决，使用其他大佬的项目 https://github.com/kanshufan-1107/HsModConfigManager

**Comment by lacanzizek** [comment]
> 已解决，使用其他大佬的项目 https://github.com/kanshufan-1107/HsModConfigManager

怎么弄的，求解

**Comment by Stardustll** [comment]
> > 已解决，使用其他大佬的项目 https://github.com/kanshufan-1107/HsModConfigManager
> 
> 怎么弄的，求解

解压至该目录下

![Image](https://github.com/user-attachments/assets/fae1ca95-f87f-4bdc-b293-652f74a6ef63)
