### ISSUE TITLE
配置管理界面白屏，其他卡牌信息页面都正常打开

### ISSUE THREAD

**Issue by bailan999** [Pik-4/HsMod#174]
### Please check before submitting an issue/提交问题前请检查

- [X] I have searched the issues and haven't found anything relevant/我搜索了这些问题，没有找到任何相关信息
- [X] I have read the README and haven't found anything relevant/我认真阅读了README，没有找到任何相关信息
- [X] I have tried repairing Hearthstone and reinstalling HsMod according to the ReadMe, but the problem persists/我尝试过修复炉石，并按照ReadMe重新安装HsMod，但是问题依然存在。
- [X] I will upload LogOutput.log, HsMod.cfg, HsSkins.cfg /我将上传LogOutput.log, HsMod.cfg, HsSkins.cfg
- [ ] I know how to reproduce the issue which may not be specific to my device/ 我知道如何重现该问题，但该问题可能并非特定于我的设备

### Describe the bug/描述你的问题。

http://localhost:58744/配置管理界面白屏，其他卡牌信息页面都正常打开
http://localhost:58744/config/index.html  配置界面白屏 使用谷歌，IE,Edge，浏览器均无法打开

### Logs/日志

[LogOutput.log](https://github.com/user-attachments/files/18201416/LogOutput.log)

**Comment by Boquirroto** [comment]
解决了吗，我也是这个情况

**Comment by snailxyz** [comment]
me too
