### ISSUE TITLE
更为清晰明了的安装教程

### ISSUE THREAD

**Issue by Qingmuc** [Pik-4/HsMod#19]
1. 在 https://github.com/BepInEx/BepInEx/releases 下载 BepInEx_x86（目前最新地址为 https://github.com/BepInEx/BepInEx/releases/download/v5.4.21/BepInEx_x86_5.4.21.0.zip ）；
2.  将 BepInEx_x86.zip 的内容全部解压至炉石根目录 Hearthstone\ 下；
3.  在 https://unity.bepinex.dev/corlibs/2019.4.37.zip 下载 Mono ；
4.  在 https://unity.bepinex.dev/libraries/2019.4.37.zip 下载 Unity ；
5.  创建一个目录 Hearthstone\BepInEx\unstripped_corlib\  ，将 Mono.zip 和 Unity.zip 内的文件解压至 Hearthstone\BepInEx\unstripped_corlib\ 下；
6.  用编辑器（记事本）打开 Hearthstone\doorstop_config.ini ，在 dllSearchPathOverride= 后添加 BepInEx\unstripped_corlib ；
7.  在 https://github.com/sinai-dev/BepInExConfigManager/releases 下载 BepInExConfigManager.Mono （目前最新地址为 https://github.com/sinai-dev/BepInExConfigManager/releases/download/1.3.0/BepInExConfigManager.Mono.zip ）；
8.  将 BepInExConfigManager.Mono 内的文件解压至 Hearthstone\BepInEx\ 下；
9.  在 https://github.com/Pik-4/HsMod/releases/download/123/HsMod.dll 下载 HsMod.dll ；
10.  创建一个目录 Hearthstone\BepInEx\plugins ，将 HsMod.dll 解压至 Hearthstone\BepInEx\plugins 下。

**Comment by Qingmuc** [comment]
修正：
将第3、4步修改为：
3. 在 https://github.com/Pik-4/HsMod/releases 下载 Source code (zip) ；
4. 创建一个目录 Hearthstone\BepInEx\unstripped_corlib\ ，将 Source code (zip) 中的 HsMod\LibUnityMono 内的文件解压至 Hearthstone\BepInEx\unstripped_corlib\ 下；

**Comment by Mrsun2022** [comment]
为什么我们不考虑做一个整合包

**Comment by max551211114** [comment]
> 1. 在 https://github.com/BepInEx/BepInEx/releases 下载 BepInEx_x86（目前最新地址为 https://github.com/BepInEx/BepInEx/releases/download/v5.4.21/BepInEx_x86_5.4.21.0.zip ）；
> 2. 将 BepInEx_x86.zip 的内容全部解压至炉石根目录 Hearthstone\ 下；
> 3. 在 https://unity.bepinex.dev/corlibs/2019.4.37.zip 下载 Mono ；
> 4. 在 https://unity.bepinex.dev/libraries/2019.4.37.zip 下载 Unity ；
> 5. 创建一个目录 Hearthstone\BepInEx\unstripped_corlib\  ，将 Mono.zip 和 Unity.zip 内的文件解压至 Hearthstone\BepInEx\unstripped_corlib\ 下；
> 6. 用编辑器（记事本）打开 Hearthstone\doorstop_config.ini ，在 dllSearchPathOverride= 后添加 BepInEx\unstripped_corlib ；
> 7. 在 https://github.com/sinai-dev/BepInExConfigManager/releases 下载 BepInExConfigManager.Mono （目前最新地址为 https://github.com/sinai-dev/BepInExConfigManager/releases/download/1.3.0/BepInExConfigManager.Mono.zip ）；
> 8. 将 BepInExConfigManager.Mono 内的文件解压至 Hearthstone\BepInEx\ 下；
> 9. 在 https://github.com/Pik-4/HsMod/releases/download/123/HsMod.dll 下载 HsMod.dll ；
> 10. 创建一个目录 Hearthstone\BepInEx\plugins ，将 HsMod.dll 解压至 Hearthstone\BepInEx\plugins 下。

为什么我没有doorstop_config.ini 文件？

**Comment by httpsColon** [comment]
不是 将项目目录HsMod/LibUnityMono下所有dll复制到unstripped_corlib目录下 ？

**Comment by GitGoooo** [comment]
开启插件以后，炉石会闪退怎么办，直接就进不去了，删掉config才能进去

**Comment by Sumuqiu32** [comment]
> > 1. 在 https://github.com/BepInEx/BepInEx/releases 下载 BepInEx_x86（目前最新地址为 https://github.com/BepInEx/BepInEx/releases/download/v5.4.21/BepInEx_x86_5.4.21.0.zip ）;
> > 2. 将 BepInEx_x86.zip 的内容全部解压至炉石根目录 Hearthstone\ 下;
> > 3. 在 https://unity.bepinex.dev/corlibs/2019.4.37.zip 下载 Mono ;
> > 4. 在 https://unity.bepinex.dev/libraries/2019.4.37.zip 下载 Unity ;
> > 5. 创建一个目录 Hearthstone\BepInEx\unstripped_corlib\ ，将 Mono.zip 和 Unity.zip 内的文件解压至 Hearthstone\BepInEx\unstripped_corlib\ 下;
> > 6. 用编辑器（记事本）打开 Hearthstone\doorstop_config.ini ，在 dllSearchPathOverride= 后添加 BepInEx\unstripped_corlib ;
> > 7. 在 https://github.com/sinai-dev/BepInExConfigManager/releases 下载 BepInExConfigManager.Mono （目前最新地址为 https://github.com/sinai-dev/BepInExConfigManager/releases/download/1.3.0/BepInExConfigManager.Mono.zip ）;
> > 8. 将 BepInExConfigManager.Mono 内的文件解压至 Hearthstone\BepInEx\ 下;
> > 9. 在 https://github.com/Pik-4/HsMod/releases/download/123/HsMod.dll 下载 HsMod.dll ;
> > 10. 创建一个目录 Hearthstone\BepInEx\plugins ，将 HsMod.dll 解压至 Hearthstone\BepInEx\plugins 下。
> 
> 为什么我没有doorstop_config.ini 文件？

下[BepInEx 5.4.23.2]win版本就有 6是预先版，还没完成可能

**Comment by kotlinmark** [comment]
HI，为什么我按f5调不出来ui

**Comment by qingming1265** [comment]
> > > 1. 在 https://github.com/BepInEx/BepInEx/releases 下载 BepInEx_x86（目前最新地址为 https://github.com/BepInEx/BepInEx/releases/download/v5.4.21/BepInEx_x86_5.4.21.0.zip ）;
> > > 2. 将 BepInEx_x86.zip 的内容全部解压至炉石根目录 Hearthstone\ 下;
> > > 3. 在 https://unity.bepinex.dev/corlibs/2019.4.37.zip 下载 Mono ;
> > > 4. 在 https://unity.bepinex.dev/libraries/2019.4.37.zip 下载 Unity ;
> > > 5. 创建一个目录 Hearthstone\BepInEx\unstripped_corlib\ ，将 Mono.zip 和 Unity.zip 内的文件解压至 Hearthstone\BepInEx\unstripped_corlib\ 下;
> > > 6. 用编辑器（记事本）打开 Hearthstone\doorstop_config.ini ，在 dllSearchPathOverride= 后添加 BepInEx\unstripped_corlib ;
> > > 7. 在 https://github.com/sinai-dev/BepInExConfigManager/releases 下载 BepInExConfigManager.Mono （目前最新地址为 https://github.com/sinai-dev/BepInExConfigManager/releases/download/1.3.0/BepInExConfigManager.Mono.zip ）;
> > > 8. 将 BepInExConfigManager.Mono 内的文件解压至 Hearthstone\BepInEx\ 下;
> > > 9. 在 https://github.com/Pik-4/HsMod/releases/download/123/HsMod.dll 下载 HsMod.dll ;
> > > 10. 创建一个目录 Hearthstone\BepInEx\plugins ，将 HsMod.dll 解压至 Hearthstone\BepInEx\plugins 下。
> > 
> > 
> > 为什么我没有doorstop_config.ini 文件？
> 
> 下[BepInEx 5.4.23.2]win版本就有 6是预先版，还没完成可能



> > > 1. 在 https://github.com/BepInEx/BepInEx/releases 下载 BepInEx_x86（目前最新地址为 https://github.com/BepInEx/BepInEx/releases/download/v5.4.21/BepInEx_x86_5.4.21.0.zip ）;
> > > 2. 将 BepInEx_x86.zip 的内容全部解压至炉石根目录 Hearthstone\ 下;
> > > 3. 在 https://unity.bepinex.dev/corlibs/2019.4.37.zip 下载 Mono ;
> > > 4. 在 https://unity.bepinex.dev/libraries/2019.4.37.zip 下载 Unity ;
> > > 5. 创建一个目录 Hearthstone\BepInEx\unstripped_corlib\ ，将 Mono.zip 和 Unity.zip 内的文件解压至 Hearthstone\BepInEx\unstripped_corlib\ 下;
> > > 6. 用编辑器（记事本）打开 Hearthstone\doorstop_config.ini ，在 dllSearchPathOverride= 后添加 BepInEx\unstripped_corlib ;
> > > 7. 在 https://github.com/sinai-dev/BepInExConfigManager/releases 下载 BepInExConfigManager.Mono （目前最新地址为 https://github.com/sinai-dev/BepInExConfigManager/releases/download/1.3.0/BepInExConfigManager.Mono.zip ）;
> > > 8. 将 BepInExConfigManager.Mono 内的文件解压至 Hearthstone\BepInEx\ 下;
> > > 9. 在 https://github.com/Pik-4/HsMod/releases/download/123/HsMod.dll 下载 HsMod.dll ;
> > > 10. 创建一个目录 Hearthstone\BepInEx\plugins ，将 HsMod.dll 解压至 Hearthstone\BepInEx\plugins 下。
> > 
> > 
> > 为什么我没有doorstop_config.ini 文件？
> 
> 下[BepInEx 5.4.23.2]win版本就有 6是预先版，还没完成可能

这个9点开404了

**Comment by zzzSEA** [comment]
您好 大佬， 我按照你的步骤来的，但是不知道什么原因，没办法启动游戏了，是因为版本问题嘛 @qingming1265
