### ISSUE TITLE
在MacOS上按下F4未能正确输出全部皮肤信息

### ISSUE THREAD

**Issue by Livelongwer** [Pik-4/HsMod#20]
如图
![screenshot_38873](https://user-images.githubusercontent.com/102666931/225693812-641e3028-9f09-41f8-b359-6411e9ea2818.png)
LogOutput内并没有全部皮肤信息
也没有其他文件可以查看皮肤信息

**Comment by Pik-4** [comment]
通过web查看呢？

**Comment by Livelongwer** [comment]
在哪里，我没有找到（

**Comment by Livelongwer** [comment]
log里面到是有一个这个https://h5.cyol.com/special/daxuexi/fe3ao1cm3k/images/end.jpg
但这个好像不是

**Comment by Livelongwer** [comment]
找到了，web端可以查看，已经解决了，麻烦您这么晚还看github了，十分感谢
