### ISSUE TITLE
MacOS的HsMod不能通过添加多值映射来实现游戏内随机皮肤效果

### ISSUE THREAD

**Issue by Livelongwer** [Pik-4/HsMod#21]
如图
![screenshot_39121](https://user-images.githubusercontent.com/102666931/226151430-0f1cefea-589e-4be2-8bce-2865ec84dba1.png)

我在符文法师卡德加（97876）后添加了多个皮肤映射，但游戏内只显示了第一串映射（82519）艾萨拉女王的皮肤，后面很多皮肤都没有达到随机，需要在HsSkins.cfg内更改保存后按下F4后游戏内模拟拔线才能手动换皮，而且字符也都是半角字符

**Comment by Pik-4** [comment]
这个功能目前还没有完善，理论上写起来也不麻烦，但炉石没了，也就随缘更新了...

**Comment by Livelongwer** [comment]
好的，但我今天上线好像又能用了（2333
具体不知道什么情况，但现在能用了，不过也感谢回复了
您的mod做的十分好，可惜遇到暴雪这个东西了Orz

**Comment by Pik-4** [comment]
目前对局结束会重新随机一次皮肤映射（纯随机，有概率与上次结果一样）。
