### ISSUE TITLE
咨询个问题

### ISSUE THREAD

**Issue by onns** [Pik-4/HsMod#22]
免战网登录的功能需要每次都跟版本修改嘛，比较想独立的搞一个这个功能，因为外网卡不多，一个号只能玩一个卡组，来回切战网太麻烦了

**Comment by Pik-4** [comment]
不失效就不用改

**Comment by onns** [comment]
啊可能我没描述清楚，因为HsMod.dll不是会随着炉石发布版本而更新嘛？

有没有啥办法，可以让命令行登录这个功能不用随着版本更新呢

**Comment by Pik-4** [comment]
HsMod.dll不会随着炉石版本更新...

**Comment by onns** [comment]
那你发的release是...
