### ISSUE TITLE
强制金卡特效导致卡牌发生变形效果时卡面不变

### ISSUE THREAD

**Issue by ShawSun-thu** [Pik-4/HsMod#28]
设置里开启强制金卡特效后，当使用如“能量塑形师”，“不稳定的异变”等卡牌将手牌或场上的卡牌变形时，卡面不会变化（卡牌描述正常）
有例外情况：变成后如果有钻石特效则是正常的

**Comment by Pik-4** [comment]
进化/退化都会有这个问题，需要重新加载相关资源。目前相关接口还没有找到，等后续有缘更新吧。

**Comment by Pik-4** [comment]
已尝试修复，如果还有问题，请继续反馈。

**Comment by ShawSun-thu** [comment]
场上卡牌变形确实没有问题了！
手牌变形时，卡面问题依然存在，包括：
1. 百变泽鲁斯之类的每回合在手牌中自动变形的卡牌；
2. 注能完成的卡牌
3. 能量塑形师（法师职业卡）使手牌法术发生变化

**Comment by Pik-4** [comment]
已尝试修复。1我是用变色龙测试，目前没发现问题。
