### ISSUE TITLE
能否支持移除借用套牌弹窗？

### ISSUE THREAD

**Issue by xsshk** [Pik-4/HsMod#30]
功能出发点：临近新版本，此套牌会在下个版本更新，届时将包含新版本卡牌内容。如果当前版本不选择开启，则无法再进行排名模式游戏。
如需提供弹窗账号，我可以提供。

弹窗如下：
![image](https://github.com/Pik-4/HsMod/assets/71780423/c2436563-7815-44d3-9baa-017960e591c0)

**Comment by Pik-4** [comment]
1. 这个理论上可以屏蔽，但不确定屏蔽后是否会有其它问题。
2. 我没有相关账号，要定位这个弹窗比较麻烦，最近没啥有时间更新，要更新估计也得很久之后了...

**Comment by Pik-4** [comment]
已添加，`游戏内消息`设置为`false`即可。
