### ISSUE TITLE
按照readme安装后启动无反应

### ISSUE THREAD

**Issue by hahah32121** [Pik-4/HsMod#34]
把文件放好进游戏后，按f5f4没有反应，请问可能是什么原因？

**Comment by hahah32121** [comment]
<img width="323" alt="屏幕截图 2023-09-08 013605" src="https://github.com/Pik-4/HsMod/assets/144376152/d4ab687e-65e8-4eaf-9e12-a344cf2ccfeb">
<img width="446" alt="屏幕截图 2023-09-08 013515" src="https://github.com/Pik-4/HsMod/assets/144376152/20954217-38f2-462c-93ad-08cb203be6ec">
这是BeplnEx文件夹里面的，应该没错？

**Comment by Pik-4** [comment]
Windows暂未发现问题，建议阅读readme自行分析...
