### ISSUE TITLE
卡牌最高特效无效

### ISSUE THREAD

**Issue by saleewisdom** [Pik-4/HsMod#35]
炉石版本：27.4.0.185749
HS版本：4.2.0.0

F5启用，使用卡牌最高特效（onlymy），该功能无效，进入对局后卡牌仍然是普通的特效；
但强制金卡（onlymy）可用，启用后人物与卡牌全部变为金色；

在启用卡牌最高特效（onlymy）时，其余参数均为默认参数，未变更；
保存后重启游戏，重启对局，该功能均无法正常使用；

**Comment by Pik-4** [comment]
目前并未发现有该问题，卡牌特效不会超出已有特效。
![Hearthstone Screenshot 09-22-23 00 28 36](https://github.com/Pik-4/HsMod/assets/88079004/528e4863-eda4-4c91-9c08-8ce3c805ac88)
