### ISSUE TITLE
开局对战的时候，幸运币是卡背对着自己的，并且在一局对战中，抽到了不属于这个套牌里面的牌。

### ISSUE THREAD

**Issue by jieqiyue** [Pik-4/HsMod#36]
开局幸运币如下：
![image](https://github.com/Pik-4/HsMod/assets/53082256/fda4d0e6-b736-44af-b2a7-4b79a7df976c)
后面，在一个回合的时候，这个幸运币当我要使用的时候，竟然还提醒我法力值不够！我用幸运币还需要法力值吗
但是这张截图我没保存下来

另外一个问题：
另外那局我玩的是术士，但是抽到了好几张不属于我那个套牌里面的牌，特别奇怪

而且感觉开了这个插件之后，变卡了不少，比如说结算的时候。

还需要什么日志吗？我可以提供

**Comment by Pik-4** [comment]
检查一下hsmod是否开启'皮肤'相关配置，检查“卡牌追踪”，“卡牌揭示”，“观战展示卡牌”，“快速战斗”选项是否关闭。必要时可以在设置里禁用插件，重连验证测试。

日志的话可能是logoutput（bepinex日志），（hearthone_xxxx）（logs目录下炉石日志）。

其他就是检查插件冲突的问题。另，记牌器也可能导致游戏变卡。

**Comment by jieqiyue** [comment]
> 检查一下hsmod是否开启'皮肤'相关配置，检查“卡牌追踪”，“卡牌洞察”，“战战展示卡牌”，“快速战斗”选项是否可以关闭。必要时在设置里取消插件，重连验证测试。
> 
> 日志的话可能是logoutput（bepinex日志），（hearthone_xxxx）（logs目录下炉石日志）。
> 
> 其他就是检查插件冲突的问题。另外，记牌器也可能导致游戏变卡。

可能是因为“卡牌追踪”，“卡牌洞察”，“战战展示卡牌”，“快速战斗”这些选项被打开，所以导致的幸运币翻面和抽到不是本卡组的卡牌吗

**Comment by Pik-4** [comment]
最多是幸运币翻面，抽到不是本卡组的卡原因未知。可以考虑一下双方卡组问题。

**Comment by jieqiyue** [comment]
![image](https://github.com/Pik-4/HsMod/assets/53082256/5459d7c9-c74a-434b-b9cf-a6c5770f5d07)
不知道为什么，开了插件之后，不能购买卡牌包，点那个购买屏幕就会变成下面这样，但是不能购买、
![image](https://github.com/Pik-4/HsMod/assets/53082256/6a9ecbe2-9573-40f7-9261-c635465ec902)

**Comment by jieqiyue** [comment]
如果关闭插件就能购买了

**Comment by Pik-4** [comment]
> ![image](https://user-images.githubusercontent.com/53082256/270962693-5459d7c9-c74a-434b-b9cf-a6c5770f5d07.png) 不知道为什么，开了插件之后，不能购买卡牌包，点那个购买屏幕就会变成下面这样，但是不能购买、 ![image](https://user-images.githubusercontent.com/53082256/270963327-6a9ecbe2-9573-40f7-9261-c635465ec902.png)

未发现有该问题。
![Hearthstone Screenshot 09-27-23 20 39 33](https://github.com/Pik-4/HsMod/assets/88079004/661ec49c-f1f3-4be5-9c61-681d3b31597a)

**Comment by jieqiyue** [comment]
有五六天没玩了，今天打开游戏，发现插件好像不运行了，按f4，f5都没反应，这得怎么排查啊

**Comment by jieqiyue** [comment]
![image](https://github.com/Pik-4/HsMod/assets/53082256/ea4050d3-5f33-4838-9d12-670d9262d5f8)

**Comment by jieqiyue** [comment]
![image](https://github.com/Pik-4/HsMod/assets/53082256/94b82b15-adad-4b1d-b400-5b455ec02133)

**Comment by Pik-4** [comment]
插件正常的话，炉石本身的ExceptionReporter会被屏蔽。你这种情况目测是网络问题。如果插件F4无反应，建议更新插件（少数情况需要更新lib文件）。
