### ISSUE TITLE
关于MAC使用token绕过战网登录的问题

### ISSUE THREAD

**Issue by Whi8per** [Pik-4/HsMod#37]
RT，配置client.config后，运行run_bepinex.sh，跳出游戏界面，但每次都提示网络问题，BepInex也没有正常运行，没有生成BepInex/config等文件夹
同环境下测试了人类一败涂地等unity游戏，BepInex正常运行，也生成了BepInex/config等文件夹，F5也能呼出菜单
在windows10环境下，运行炉石脚本也是正常的
猜测是token登录问题，游戏没有完全打开，导致BepInx无法注入，但不知道如何解决

Login.out如下
I 14:39:10.4633170 Beginning processing login challenges
I 14:39:12.7112310 Processing challenge, previous login challenge attempts 0
I 14:39:12.9426120 Processing challenge, previous login challenge attempts 1
I 14:39:13.2039300 Multiple attempts likely failed with same auth token, clearing authentication data
I 14:39:13.2039300 Processing challenge, previous login challenge attempts 2
I 14:39:13.2039300 A repeated token was retrieved when disallowed. Setting to null token for failure
I 14:39:13.2469250 A repeated token was retrieved when disallowed. Setting to null token for failure
I 14:39:13.2722270 A repeated token was retrieved when disallowed. Setting to null token for failure
I 14:39:13.3216660 A repeated token was retrieved when disallowed. Setting to null token for failure
I 14:39:13.3381890 A repeated token was retrieved when disallowed. Setting to null token for failure
E 14:39:13.3754310 Failed to get token to respond to login challenge

设备：iMAC
芯片：M1
系统：macOS 13.5.2 (22G91)

**Comment by Pik-4** [comment]
炉石启动顺序： BepInEx注入，配置插件、HsMod等插件加载，Hook炉石原有方法：允许炉石接受token，解析token，登录炉石。

> 允许使用VerifyWebCredentials登录（亦支持命令行启动，不需要启动战网）。

因此，可以移除client.config，直接利用`./hearthstone.exe token`（mac下应该是`run_bepinex.sh token`）进行启动（Windows目前测试没有问题，手头没有MAC无法验证）。

因此建议检查一下BepInEx的启动日志，看看是否有其他信息。

**Comment by Whi8per** [comment]
运行sh脚本后，跳出炉石无法通过暴雪服务进行登录的界面，然后的BepInEx目录下没有生成任何新文件夹和文件夹，所以找不到cfg等文件

同配置环境，仅修改executable_name=""，复制到人类一败涂地根目录下，运行sh脚本之后，BepInEx就能自动生成LogOutput.log等文件和config等文件夹，steam添加启动项，"~/Human Fall Flat/run_bepinex.sh" "%command% 之后一切都可以正常运行

所以感觉是token的问题，无法登陆，试了./run_bepinex.sh token的方式，终端报错

2023-09-28 16:18:55.470 defaults[44707:487562] 
The domain/default pair of (KR-b59c4be26af3072b1e49803c0bd01fab-34996370/Contents/Info, CFBundleExecutable) does not exist
/Applications/Hearthstone/run_bepinex.sh: line 91: cd: **KR-b59c4be26af3072b1e49803c0bd01fab-34996370**/Contents: No such file or directory
/MacOS
Cannot identify executable type (got cannot open `/MacOS' (No such file or directory))!
Please create an issue at https://github.com/BepInEx/BepInEx/issues.

**Comment by Pik-4** [comment]
这里有份完整的[HsMod_4.2.0.0_Full_Mac.zip](https://github.com/Pik-4/HsMod/releases/download/142/HsMod_4.2.0.0_Full_Mac.zip)，修改client.config再看看，另外，注意token安全性。

看了一下sh脚本，参数应该加在run_bepinex.sh结尾"`${executable_path}" "$@" "token"`。

**Comment by Whi8per** [comment]
感谢感谢，不过还是同样的问题，bepinex没有加载，我出现的问题应该和#8和#32相同，这是运行run_bepinex.sh之后的终端代码

[Terminal Saved Output.txt](https://github.com/Pik-4/HsMod/files/12747614/Terminal.Saved.Output.txt)

**Comment by onns** [comment]
有用记牌器吗

**Comment by Livelongwer** [comment]
没有使用记牌器

**Comment by Pik-4** [comment]
参考Linux的配置看看？在linux系统上，炉石使用的似乎仍是bepinex提供的unity和mono.
