### ISSUE TITLE
求助!求助！请问这个快捷键是什么啊，我用了这个快捷键，但是好像没用哇

### ISSUE THREAD

**Issue by jieqiyue** [Pik-4/HsMod#38]
求助!求助！请问这个快捷键是什么啊，我用了这个快捷键的，但是没用。UpArrow，应该就是方向键向上吧。但是我按了，没用。
![image](https://github.com/Pik-4/HsMod/assets/53082256/96c2bfc1-a742-44cc-ae09-af739a8436be)

**Comment by jieqiyue** [comment]
而且在用了变速齿轮之后，而且好像变身卡之后，这个技能不会变
![image](https://github.com/Pik-4/HsMod/assets/53082256/0548ec40-9c81-4265-a13f-87ce35927f94)

**Comment by Pik-4** [comment]
> 本插件在默认状态下，几乎全部的功能均需要手动开启；

快捷键默认禁用，需要手动开启相关设置；至于技能图标问题，检查皮肤替换相关设置，后续有时间会更新替换逻辑。
