### ISSUE TITLE
新版本HSMOD仍然无法在mac上使用

### ISSUE THREAD

**Issue by Livelongwer** [Pik-4/HsMod#39]
[终端存储的输出.txt](https://github.com/Pik-4/HsMod/files/13447710/default.txt)
![screenshot_729](https://github.com/Pik-4/HsMod/assets/102666931/0a355c7f-47d0-4d2f-8981-98f7728ef71b)
启动后是这样，并且BepInEx目录下没有配置文件以及log产生

**Comment by Pik-4** [comment]
要不你尝试一下隔壁的[MixMod](https://github.com/DeNcHiK3713/MixMod/releases)...更倾向于BepInEx本身的问题。
我手边依然没有Mac，抱歉暂时无法修复。

**Comment by Pik-4** [comment]
参考Linux的配置看看？在linux系统上，炉石使用的似乎仍是bepinex提供的unity和mono.
