### ISSUE TITLE
mac 版本找不到 HSMod.cfg

### ISSUE THREAD

**Issue by zyl24** [Pik-4/HsMod#41]
出现了 #8 的问题，确定找不到 HSMod.cfg文件。

**Comment by Pik-4** [comment]
请提供更多信息，我用Linux版炉石正常（Linux版炉石由Mac移植而来）
![1](https://github.com/Pik-4/HsMod/assets/88079004/aa7feec0-8479-4fd1-95e2-fb5207bd0854)

**Comment by zyl24** [comment]
> 请提供更多信息，我用Linux版炉石正常（Linux版炉石由Mac移植而来） ![1](https://private-user-images.githubusercontent.com/88079004/308541725-aa7feec0-8479-4fd1-95e2-fb5207bd0854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTMyNjUsIm5iZiI6MTcwOTIxMjk2NSwicGF0aCI6Ii84ODA3OTAwNC8zMDg1NDE3MjUtYWE3ZmVlYzAtODQ3OS00ZmQxLTk1ZTItZmI1MjA3YmQwODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEzMjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MWRmMDE2ZDA4ZDRjNWNlZWJiMDFkNjcyNzhiODhhZWI3OWVkM2EzMzBjZjY1YzJlZmExMDVkOWM2ODJkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMLrmHuaay_xbdjAOs7PPsCkC_EFW8yMtaOvgz1s1zk)
<img width="1792" alt="截屏2024-02-29 21 30 19" src="https://github.com/Pik-4/HsMod/assets/59046279/50a6a3a6-828a-44dc-9830-49799bc81603">

按照教程进行配置之后，通过终端输入 ./run_bepinex.sh ，能够启动游戏，但是遇到了 #8 同样的问题，无法通过暴雪战网服务器进行登录。终端里也给出同样的报错信息
`Found UnityPlayer, hooking into it instead
Failed to hook jit_init_version, ignoring it. Error: no such function: mono_jit_init_version`
我本来准备尝试 #8 里的方法，但是发现本地没有 config 这个文件夹，也无法找到 HSMod.cfg 文件。
<img width="646" alt="截屏2024-02-29 21 32 53" src="https://github.com/Pik-4/HsMod/assets/59046279/98bb72ee-13c1-4bf7-a9ff-fcc5da3bfc75">
我尝试过自己先创建一个空的 config 文件夹，但是再次运行后发现依然是同样的问题，也没有自动生成 HSMod.cfg 文件。
