### ISSUE TITLE
怎么确定当前版本可以继续使用哇？

### ISSUE THREAD

**Issue by onns** [Pik-4/HsMod#42]
如果用旧版本的插件应该会被官方检测出来吧？所以怎么判断需不需要等你更新呢

**Comment by Pik-4** [comment]
看日志没报错就能用，理论上旧版本检测不到（不信，你可以修复炉石试试）

**Comment by onns** [comment]
话说，我留下一个邮箱给你，后续可以帮你验证在win和mac下是否生效？onns@onns.xyz
当然，如果需要一起共建的地方也可以喊我，感谢开源
