### ISSUE TITLE
怎么实现最高特效到异画而不是钻石

### ISSUE THREAD

**Issue by Boquirroto** [Pik-4/HsMod#43]
目前插件是支持最高特效到钻石吧，可以开异画但是优先还是钻石，如果我想只用异画或者是优先异画有没有办法实现呢作者大大

**Comment by Pik-4** [comment]
按照炉石的设定特效排名是钻石>异画=金卡>普通，程序也是按照这个逻辑处理，后续如果异画需求多的话，可以考虑重构特效判断逻辑（~~现在特效判断代码纯纯的屎山~~）

**Comment by Boquirroto** [comment]
> 按照炉石的设定特效排名是钻石>异画=金卡>普通，程序也是按照这个逻辑处理，后续如果异画需求多的话，可以考虑重构特效判断逻辑（~现在特效判断代码纯纯的屎山~）

感谢作者大大的回复，另外如果更新插件是替换那个dll后缀的文件吗，不是很清楚

**Comment by Pik-4** [comment]
> > 按照炉石的设定特效排名是钻石>异画=金卡>普通，程序也是按照这个逻辑处理，后续如果异画需求多的话，可以考虑重构特效判断逻辑（~现在特效判断代码纯纯的屎山~）
> 
> 感谢作者大大的回复，另外如果更新插件是替换那个dll后缀的文件吗，不是很清楚

没有太大的更新只需要替换hsmod.dll即可，部分情况下还需要更新unity相关dll（炉石的unity版本发生变化）

**Comment by Boquirroto** [comment]
> > > 按照炉石的设定特效排名是钻石>异画=金卡>普通，程序也是按照这个逻辑处理，后续如果异画需求多的话，可以考虑重构特效判断逻辑（~现在特效判断代码纯纯的屎山~）
> > 
> > 
> > 感谢作者大大的回复，另外如果更新插件是替换那个dll后缀的文件吗，不是很清楚
> 
> 没有太大的更新只需要替换hsmod.dll即可，部分情况下还需要更新unity相关dll（炉石的unity版本发生变化）

这个unity版本在哪看呀 还有当前我当前使用的hsmod版本在哪看 我是小白对这方面不了解问题有点多不好意思 不过插件用了几个月没更新倒是一点问题都没有 做的非常好
