### ISSUE TITLE
Translation and Fork of Your Game Mod

### ISSUE THREAD

**Issue by radik097** [Pik-4/HsMod#46]
**Dear PIk-4**,

I hope this message finds you well. I am writing to inform you of a recent project I undertook involving your game mod. Inspired by the creativity and functionality of your work, I decided to translate the mod into English to make it more accessible to a broader audience.

To accomplish this, I utilized **Python for automatic translation**, ensuring a seamless and efficient process. The translated version of the mod is now available in a forked repository on GitHub:

[https://github.com/radik097/HsMod_en/tree/master](https://github.com/radik097/HsMod_en/tree/master)

I believe this English version will help in expanding the mod’s reach and enhancing the gaming experience for English-speaking players. I invite you to review the translation and share your thoughts on the modifications. Your feedback is highly valuable, and I am open to making further improvements based on your suggestions.

Thank you for your original work on the mod, which served as a significant inspiration for this project. I look forward to hearing your opinions and hope for a positive collaboration.

Best regards,

Rodion
---

您好！我希望我的消息能让您感到愉快。我写信给您是想告诉您关于我最近参与的一个项目——涉及到您的游戏MOD。受到您作品的创意和功能性的启发，我决定将MOD翻译成英文，以便让更多的玩家能够理解和享受。

为了实现这一目标，我使用了**Python进行自动翻译**，确保了翻译过程的流畅和高效。现在，MOD的英文版本已经可在GitHub上的一个分支仓库中找到：

[https://github.com/radik097/HsMod_en/tree/master](https://github.com/radik097/HsMod_en/tree/master)

我相信，这个英文版本将有助于扩大MOD的受众范围，提升英语玩家的游戏体验。我诚邀您审阅这个翻译，并分享您对于这些修改的看法。您的反馈极其宝贵，我愿意根据您的建议进行进一步的改进。

感谢您对MOD原作的贡献，它为这个项目提供了重要的灵感。我期待听到您的意见，并希望能有一个积极的合作。

此致，

敬礼！

罗迪恩

---

**Comment by Pik-4** [comment]
Thanks for your PR. I have added multi-language support. Currently, only the configuration part has been translated. Although it is not perfect yet, you can try it.
