### ISSUE TITLE
如何通过命令行参数方式登录指定区服？

### ISSUE THREAD

**Issue by ferryboy001** [Pik-4/HsMod#49]
我是一名盲人玩家。关于我如何玩炉石就不细说了，主要就是使用命令登录时，我之提供了 token，然而默认登录的是欧服，想请问有没有办法可以指定区服？

**Comment by ferryboy001** [comment]
我明白了，token 前两个字符是区域代码，我之前获取错了，所以出问题了。

后来我其实尝试过把前两个字符修改为 US 但不起作用。

刚刚发完 issue 就怀疑是自己当时没使用魔法的原因，然后就得到了正确的 token。

好了，我应该可以把这个 issue 关掉了。

**Comment by freechao123** [comment]
> 我明白了，token 前两个字符是区域代码，我之前获取错了，所以出问题了。
> 
> 后来我其实尝试过把前两个字符修改为 US 但不起作用。
> 
> 刚刚发完 issue 就怀疑是自己当时没使用魔法的原因，然后就得到了正确的 token。
> 
> 好了，我应该可以把这个 issue 关掉了。

登录以后是隐身状态吗
