### ISSUE TITLE
1.4.1.3 web 502错误

### ISSUE THREAD

**Issue by z-henry** [Pik-4/HsMod#5]
1.4.1.3
无法访问web 错误502
telnet不通

**Comment by Pik-4** [comment]
旧版本也有吗？

**Comment by z-henry** [comment]
我挨个回退下，可能不排除可能是我本地环境的问题

**Comment by Pik-4** [comment]
那可能没有做try，catch处理，导致报错未执行server启动，理论上游戏内按F4能解决
