### ISSUE TITLE
炉石新版本更新之后出现闪退问题

### ISSUE THREAD

**Issue by LinLin00000000** [Pik-4/HsMod#52]
酒馆战棋在升到四本或者五本之后，只要一刷新或者买怪游戏就会直接闪退，重连游戏之后再操作也会反复闪退。

删除了相关.cfg配置文件（一般位于BepInEx\config\）也没用，插件在游戏内都没开启，仅仅是安装就会出现问题。

将插件删除之后才正常。

**Comment by zwxbest** [comment]
我也是，打完一局对战就闪退。然后再进去再打一局，又闪退。

**Comment by Pik-4** [comment]
有错误日志吗？

**Comment by zwxbest** [comment]
> 有错误日志吗？

日志看哪里？需要手动打开吗？

我看LogOutput.log没啥error信息，日志内容也很少。

目前我是进去打完一局对战在结算页面点一下继续，就闪退了，

试了四五次，100%触发。

**Comment by Pik-4** [comment]
Unity和Mono版本变化，已在`266b44c08a7142f92e76f0878bef6ef45a3116d2`更新。自行替换相关依赖文件。
