### ISSUE TITLE
win11 替换 266b44c08a7142f92e76f0878bef6ef45a3116d2版本的LibUnityMono文件夹下的dll文件后，启动黑屏

### ISSUE THREAD

**Issue by yang-pipi** [Pik-4/HsMod#54]
启动日志报错如图：
![Snipaste_2024-06-22_14-40-13](https://github.com/Pik-4/HsMod/assets/147571257/daec2ee7-6e9b-4a91-a98a-38340bb10ef3)

**Comment by SummerBlue-code** [comment]
#53 有解决方案，删掉winhttp.dll，并使用win_x86的[BepInEx](https://github.com/BepInEx/BepInEx/releases)

**Comment by SummerBlue-code** [comment]
我也有这个问题
