### ISSUE TITLE
设置保存失效

### ISSUE THREAD

**Issue by casualtouch** [Pik-4/HsMod#6]
一些设置类似是否启用快捷键 齿轮 自动开盒 弹出消息等等 游戏内修改设置之后退出游戏重启 不保存仍是默认设置 不管是哪个设置模版挂机的还是非挂机都不生效  奇怪的是最底下的设置修改游戏重启之后是保存了的 有点疑惑

**Comment by Pik-4** [comment]
是否还使用了其他插件，如果有，移除后再尝试。

**Comment by casualtouch** [comment]
thx 已解决 有些patch好像跟佣兵插件冲突了 移除了佣兵插件设置正常 感谢
