### ISSUE TITLE
有没有更详细的跳过战网启动炉石的教程

### ISSUE THREAD

**Issue by lacanzizek** [Pik-4/HsMod#68]
有没有更详细的跳过战网启动炉石的教程

**Comment by fltx2004** [comment]
首先根据地区不同分别用浏览器打开下面这几个链接
https://tw.battle.net/login/zh/?app=wtcg
https://kr.battle.net/login/zh/?app=wtcg
https://us.battle.net/login/en/?app=wtcg
https://eu.battle.net/login/en/?app=wtcg
分别代表
- 台湾
- 韩国
- 美国
- 欧洲

正常登录你的账号，然后浏览器会自动跳转到
http://localhost:0/?ST=US-XXXXXXXXXX
复制‘"ST="后面的内容
建立个炉石快捷方式，在属性的目标编辑框中，把获得的token放在最后，及引号后面，要有个空格，类似这样
"C:\Program Files (x86)\Hearthstone\Hearthstone.exe" US-xxxxxxxxxxxxxxxx
点击确定，这时候直接打开这个快捷方式就能玩了

**Comment by lacanzizek** [comment]
国服的url是多少呀，github的无法打开

**Comment by httpsColon** [comment]
> 首先根据地区不同分别用浏览器打开下面这几个链接 https://tw.battle.net/login/zh/?app=wtcg https://kr.battle.net/login/zh/?app=wtcg https://us.battle.net/login/en/?app=wtcg https://eu.battle.net/login/en/?app=wtcg 分别代表
> 
> * 台湾
> * 韩国
> * 美国
> * 欧洲
> 
> 正常登录你的账号，然后浏览器会自动跳转到 http://localhost:0/?ST=XX-XXXXXXXXXX 复制‘"ST="后面的内容 建立个炉石快捷方式，在属性的目标编辑框中，把获得的token放在最后，及引号后面，要有个空格，类似这样 "C:\Program Files (x86)\Hearthstone\Hearthstone.exe" US-xxxxxxxxxxxxxxxx 点击确定，这时候直接打开这个快捷方式就能玩了

登录后跳转到战网账号设置了啊

**Comment by httpsColon** [comment]
> 首先根据地区不同分别用浏览器打开下面这几个链接 https://tw.battle.net/login/zh/?app=wtcg https://kr.battle.net/login/zh/?app=wtcg https://us.battle.net/login/en/?app=wtcg https://eu.battle.net/login/en/?app=wtcg 分别代表
> 
> * 台湾
> * 韩国
> * 美国
> * 欧洲
> 
> 正常登录你的账号，然后浏览器会自动跳转到 http://localhost:0/?ST=XX-XXXXXXXXXX 复制‘"ST="后面的内容 建立个炉石快捷方式，在属性的目标编辑框中，把获得的token放在最后，及引号后面，要有个空格，类似这样 "C:\Program Files (x86)\Hearthstone\Hearthstone.exe" US-xxxxxxxxxxxxxxxx 点击确定，这时候直接打开这个快捷方式就能玩了

成功辣，原来是先登录web战网，再从那个链接进行一次验证码登录，就会跳转localhost了

**Comment by freechao123** [comment]
> > 首先根据地区不同分别用浏览器打开下面这几个链接 https://tw.battle.net/login/zh/?app=wtcg https://kr.battle.net/login/zh/?app=wtcg https://us.battle.net/login/en/?app=wtcg https://eu.battle.net/login/en/?app=wtcg 分别代表
> > 
> > * 台湾
> > * 韩国
> > * 美国
> > * 欧洲
> > 
> > 正常登录你的账号，然后浏览器会自动跳转到 http://localhost:0/?ST=XX-XXXXXXXXXX 复制‘"ST="后面的内容 建立个炉石快捷方式，在属性的目标编辑框中，把获得的token放在最后，及引号后面，要有个空格，类似这样 "C:\Program Files (x86)\Hearthstone\Hearthstone.exe" US-xxxxxxxxxxxxxxxx 点击确定，这时候直接打开这个快捷方式就能玩了
> 
> 成功辣，原来是先登录web战网，再从那个链接进行一次验证码登录，就会跳转localhost了

登录以后是隐身状态吗

**Comment by fltx2004** [comment]
没试过，没选过隐身，可以先试试在战网里隐身在重新获取token尝试

**Comment by freechao123** [comment]
> 没试过，没选过隐身，可以先试试在战网里隐身在重新获取token尝试

前提是要开启hsmod吧，我试过不开mod，启动不了吧
