### ISSUE TITLE
cn需要更换验证网关域名

### ISSUE THREAD

**Issue by z-henry** [Pik-4/HsMod#71]
本来想提pr的，不小心直接提交上来了。
accd6e7直接提交到项目上了，请审核下

**Comment by Pik-4** [comment]
国服战网炸了，暂时没法测试，目前生成了release 6.4.0.1。如果有问题，之后再修改。

**Comment by ICE-GB** [comment]
你们现在可以正常访问吗？我这里timeout :crying_cat_face:
