### ISSUE TITLE
国服排队优化？

### ISSUE THREAD

**Issue by Leiouweiyi** [Pik-4/HsMod#74]
更快的请求是否排队完成的接口。。

**Comment by Pik-4** [comment]
暂时没时间研究，似乎token登录+32倍速可以加快进入？

**Comment by freechao123** [comment]
> 暂时没时间研究，似乎token登录+32倍速可以加快进入？

大佬，可以讲解下怎么跳过战网登录吗？介绍里的看不懂，我的错

**Comment by freechao123** [comment]
> 暂时没时间研究，似乎token登录+32倍速可以加快进入？

大佬，我跳过战网弄成功了，不过cofig里的内容打开一次炉石就更新了，就得重新改一次
