### ISSUE TITLE
关于国服反作弊系统的问题

### ISSUE THREAD

**Issue by Boquirroto** [Pik-4/HsMod#78]
听说国服使用了反作弊系统，不知道是否对本mod有影响

**Comment by Pik-4** [comment]
mod本身在一定程度上屏蔽了反作弊，但不保证不封号。目前还没有仅用hsmod封号的案例。

还是那句名言，**用别怕，怕别用，封别叫**

**Comment by Boquirroto** [comment]
> mod本身在一定程度上屏蔽了反作弊，但不保证不封号。目前还没有仅用hsmod封号的案例。
> 
> 还是那句名言，**用别怕，怕别用，封别叫**
哈哈我是一直在用你的mod，也是偶然才得知国服弄了个这么个东西，我是怕mod失效的问题，不是怕封号，国服最近的操作挺凉心的
