### ISSUE TITLE
使用插件会闪退

### ISSUE THREAD

**Issue by Ink202513** [Pik-4/HsMod#79]
国服使用插件，F5有界面酒馆加速有效果 但是 第二第三回合的样子就会直接闪退游戏 本以为是和酒馆记牌器插件冲突 关闭后 再次打了一把 还是会闪退 想问下有办法解决吗

**Comment by fltx2004** [comment]
我这里是酒馆加速有效果，除了酒馆以外加速都没效果，国服

**Comment by Ink202513** [comment]
已自行解决，修复游戏后重新安装插件无闪退
