### ISSUE TITLE
英雄映射只能映射到皮肤英雄牌吗?

### ISSUE THREAD

**Issue by HiddenCirno** [Pik-4/HsMod#86]
尝试换冒险的英雄牌与可收集英雄牌, 都只有技能发生了变化, 英雄原画并没有改变, 这可能是一个bug?

**Comment by Pik-4** [comment]
皮肤映射(HsSkins.cfg)怎么写的?

**Comment by HiddenCirno** [comment]
> 皮肤映射(HsSkins.cfg)怎么写的?

number1:number2, number1是当前正在使用的皮肤ID,number2是对应的英雄牌/冒险boss牌ID,来自卡牌数据库,技能是正常变了的但是英雄头像没有变化

**Comment by Pik-4** [comment]
看了一下，英雄替换的触发规则是，英雄卡属于CardHero，并且cardId前缀满足"HERO_"时候才会替换英雄卡。技能替换先于英雄卡替换，且技能卡是从英雄卡反推出来，因此可以直接替换。
~~目测不影响体验，等有时间再修吧（英雄替换代码过于屎山）~~

**Comment by HiddenCirno** [comment]
> 看了一下，英雄替换的触发规则是，英雄卡属于CardHero，并且cardId前缀满足"HERO_"时候才会替换英雄卡。技能替换先于英雄卡替换，且技能卡是从英雄卡反推出来，因此可以直接替换。 ~目测不影响体验，等有时间再修吧（英雄替换代码过于屎山）~

原来是过滤了ID, 难怪没变)

**Comment by HiddenCirno** [comment]
> 看了一下，英雄替换的触发规则是，英雄卡属于CardHero，并且cardId前缀满足"HERO_"时候才会替换英雄卡，显然乌瑟尔不满足HERO_这个前缀。至于技能为什么会替换，是因为技能替换先于英雄卡替换，且技能卡是从英雄卡反推出来，因此可以直接替换。 ~目测不影响体验，等有时间再修吧（英雄替换代码过于屎山）~

![image](https://github.com/user-attachments/assets/031cd85e-23c4-4778-bced-9a9e488cca2d)
更神奇的事情发生了，酒馆战旗的英雄牌居然是可以正常替换的（此处为巫妖王，卡牌ID为TB_BaconShop_HERO_22，DBID为58024），这张卡的前缀显然并非hero……

**Comment by HiddenCirno** [comment]
> > 看了一下，英雄替换的触发规则是，英雄卡属于CardHero，并且cardId前缀满足"HERO_"时候才会替换英雄卡，显然乌瑟尔不满足HERO_这个前缀。至于技能为什么会替换，是因为技能替换先于英雄卡替换，且技能卡是从英雄卡反推出来，因此可以直接替换。 ~目测不影响体验，等有时间再修吧（英雄替换代码过于屎山）~
> 
> ![image](https://private-user-images.githubusercontent.com/85435395/376003446-031cd85e-23c4-4778-bced-9a9e488cca2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODc2OTUsIm5iZiI6MTcyODc4NzM5NSwicGF0aCI6Ii84NTQzNTM5NS8zNzYwMDM0NDYtMDMxY2Q4NWUtMjNjNC00Nzc4LWJjZWQtOWE5ZTQ4OGNjYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAyNDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZTJhNWVjNDdhY2IyM2NiNjY0MTQ5NTg4ODkxMWQ3ZTI0NmU0ZjE2ZmM1Zjg0ZTJjODU1Y2VlYTFiZGRkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IlE8Xg6B0IPcKBMX94DyGMim1N7jWkii_KMghcOfPgU) 更神奇的事情发生了，酒馆战旗的英雄牌居然是可以正常替换的（此处为巫妖王，卡牌ID为TB_BaconShop_HERO_22，DBID为58024），这张卡的前缀显然并非hero…… 我去读一下patcher的代码看看……话说炉石可以装ue吗？可以的话调试起来应该方便很多
简单调试了一下, 英雄牌的tag也是hero没错, 去掉了字符串检测依然没有生效, 很奇怪.....

**Comment by HiddenCirno** [comment]
> > 看了一下，英雄替换的触发规则是，英雄卡属于CardHero，并且cardId前缀满足"HERO_"时候才会替换英雄卡，显然乌瑟尔不满足HERO_这个前缀。至于技能为什么会替换，是因为技能替换先于英雄卡替换，且技能卡是从英雄卡反推出来，因此可以直接替换。 ~目测不影响体验，等有时间再修吧（英雄替换代码过于屎山）~
> 
> ![image](https://private-user-images.githubusercontent.com/85435395/376003446-031cd85e-23c4-4778-bced-9a9e488cca2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTE0NjAsIm5iZiI6MTcyODc5MTE2MCwicGF0aCI6Ii84NTQzNTM5NS8zNzYwMDM0NDYtMDMxY2Q4NWUtMjNjNC00Nzc4LWJjZWQtOWE5ZTQ4OGNjYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAzNDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMzU1ZjkxNGRmNzBjYjIxZWU5ZWZhMmFjNzM4ZTMxNTQ2N2E5NzM3M2Y3NWM1NTBmNTU0Y2ZiZTFjNzY3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HgVCCw52gwe9vZLmp5Fp1U2-nJIBIZU50jNcI2gpEOg) 更神奇的事情发生了，酒馆战旗的英雄牌居然是可以正常替换的（此处为巫妖王，卡牌ID为TB_BaconShop_HERO_22，DBID为58024），这张卡的前缀显然并非hero…… 我去读一下patcher的代码看看……话说炉石可以装ue吗？可以的话调试起来应该方便很多 简单调试了一下, 英雄牌的tag也是hero没错, 去掉了字符串检测依然没有生效, 很奇怪..... 刚才咋点成回复了= = 又试了一下, 修改默认偏好英雄之后变了, 难道是进入默认皮肤判定了? ![image](https://private-user-images.githubusercontent.com/85435395/376005619-5919c6da-c374-4437-a3ee-be4a51fede98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTE0NjAsIm5iZiI6MTcyODc5MTE2MCwicGF0aCI6Ii84NTQzNTM5NS8zNzYwMDU2MTktNTkxOWM2ZGEtYzM3NC00NDM3LWEzZWUtYmU0YTUxZmVkZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAzNDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjlkZjUyYzBjNTZhYmIwZmI5NmE3NDFlOGZmNzM1M2MwNjk4OWNkNGI3YjFhZDhjOWUyMTcwOTNmNGRkOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dFyUQhxSny706O0H7FxmtJZf_BcM1_xH59guau_5F34)

**Comment by HiddenCirno** [comment]
卧槽点错了

**Comment by HiddenCirno** [comment]
> > > 看了一下，英雄替换的触发规则是，英雄卡属于CardHero，并且cardId前缀满足"HERO_"时候才会替换英雄卡，显然乌瑟尔不满足HERO_这个前缀。至于技能为什么会替换，是因为技能替换先于英雄卡替换，且技能卡是从英雄卡反推出来，因此可以直接替换。 ~目测不影响体验，等有时间再修吧（英雄替换代码过于屎山）~
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/85435395/376003446-031cd85e-23c4-4778-bced-9a9e488cca2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTE0NjAsIm5iZiI6MTcyODc5MTE2MCwicGF0aCI6Ii84NTQzNTM5NS8zNzYwMDM0NDYtMDMxY2Q4NWUtMjNjNC00Nzc4LWJjZWQtOWE5ZTQ4OGNjYTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAzNDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMzU1ZjkxNGRmNzBjYjIxZWU5ZWZhMmFjNzM4ZTMxNTQ2N2E5NzM3M2Y3NWM1NTBmNTU0Y2ZiZTFjNzY3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HgVCCw52gwe9vZLmp5Fp1U2-nJIBIZU50jNcI2gpEOg) 更神奇的事情发生了，酒馆战旗的英雄牌居然是可以正常替换的（此处为巫妖王，卡牌ID为TB_BaconShop_HERO_22，DBID为58024），这张卡的前缀显然并非hero…… 我去读一下patcher的代码看看……话说炉石可以装ue吗？可以的话调试起来应该方便很多 简单调试了一下, 英雄牌的tag也是hero没错, 去掉了字符串检测依然没有生效, 很奇怪..... 刚才咋点成回复了= = 又试了一下, 修改默认偏好英雄之后变了, 难道是进入默认皮肤判定了? ![image](https://private-user-images.githubusercontent.com/85435395/376005619-5919c6da-c374-4437-a3ee-be4a51fede98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTE0NjAsIm5iZiI6MTcyODc5MTE2MCwicGF0aCI6Ii84NTQzNTM5NS8zNzYwMDU2MTktNTkxOWM2ZGEtYzM3NC00NDM3LWEzZWUtYmU0YTUxZmVkZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAzNDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjlkZjUyYzBjNTZhYmIwZmI5NmE3NDFlOGZmNzM1M2MwNjk4OWNkNGI3YjFhZDhjOWUyMTcwOTNmNGRkOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dFyUQhxSny706O0H7FxmtJZf_BcM1_xH59guau_5F34)
> > 问题找到了, Utils.CheckInfo.IsHero(dbid, out Assets.CardHero.HeroType res) 对黑锋骑士乌瑟尔的dbid(52235)返回了false, 因此没有进入cardID赋值
> > 这个判断语句很重要吗?
> > Utils.CheckInfo.IsHero()通过读取一个CacheHeroes判断传入的dbid是否是英雄, 而CacheHeroes来自dbf.CARDHERO, 用as看了下, 这个json似乎只包含可收藏英雄, 至于战旗为啥能生效原理不明......也许可以把这个判定语句直接注释掉了?
> > 我TM怎么又点成回复了= =
> > 这个语句用的还挺多卧槽......
> > 也许可以写一个新方法从dbid返回到cardid判断卡牌是否是英雄, 替换掉这个语句
> > 但是感觉有点蠢......先写了再说吧
> > dbid和cardid的type怎么还不一样啊卧槽, vanilla是正常英雄, honored是啥啊, 升级英雄技能?
> > 好像是默认皮肤和t2皮肤......
> > 摩戈尔在dbf源文件中的type是0(UNKNOWN), 但是log打出来是true, 应该是update中赋值了, 我再看看......
> > 破案了, 它只检查ID是否包含在dbf里, 压根就没检查herotype........= =
> > 有思路了
> > 一路追踪发现heroesmapping又有问题......我能干掉它吗= =
> > HeroesMapping.TryGetValue(GameUtils.TranslateCardIdToDbId(cardId), out int dbid)条件内嵌了一层Utils.isHero, 这个判定有意义吗......
> > 不管了, 干掉试试先
> > 我TM编译完没导入....觉了
> > 似乎是修好了
> > 呃应该是好了, 我去开个pr

开pr了

**Comment by Pik-4** [comment]
HeroesMapping是用来进行英雄替换的内部映射表....HsSkins.cfg加载完成后，就存在这里。其在每次对局结束后自动更新。
酒馆应该是单独替换的。
~~要不然怎么说这代码是屎山~~

**Comment by HiddenCirno** [comment]
> HeroesMapping是用来进行英雄替换的内部映射表....HsSkins.cfg加载完成后，就存在这里。其在每次对局结束后自动更新。 酒馆应该是单独替换的。判断加多了肯定没问题，至于为什么加判断我就不知道了。以前写的代码，只有上帝能看得懂，~所以说这代码就是屎山~

重新排查后发现不是map问题是我编译了没有替换旧版本= =忙的有点晕
调试了半天最后在utils里的ishero部分新增了一个elseif判定, 基于cardid获取tag返回true(只能处理传统对战, 无法处理酒馆和佣兵, 我写死了Hero), 但是会导致另一个问题, translatedbidtocardid可能传入null, 于是又加了一层if......
屎山是怎么形成的.jpg
总之应该是彻底修好了, 具体代码变动请看pr)

**Comment by Pik-4** [comment]
> > HeroesMapping是用来进行英雄替换的内部映射表....HsSkins.cfg加载完成后，就存在这里。其在每次对局结束后自动更新。 酒馆应该是单独替换的。判断加多了肯定没问题，至于为什么加判断我就不知道了。以前写的代码，只有上帝能看得懂，~所以说这代码就是屎山~
> 
> 重新排查后发现不是map问题是我编译了没有替换旧版本= =忙的有点晕 调试了半天最后在utils里的ishero部分新增了一个elseif判定, 基于cardid获取tag返回true(只能处理传统对战, 无法处理酒馆和佣兵, 我写死了Hero), 但是会导致另一个问题, translatedbidtocardid可能传入null, 于是又加了一层if...... 屎山是怎么形成的.jpg 总之应该是彻底修好了, 具体代码变动请看pr)

我也不知道算不算修了，反正先更新到6.5.1.0了，感兴趣可以继续开发hsmod，~~因为我时刻准备跑路~~。
另外，C#有语法糖，炉石有自己的方法。
