### ISSUE TITLE
冒险模式「狗头人与地下世界」无法强制启用卡牌特效

### ISSUE THREAD

**Issue by HiddenCirno** [Pik-4/HsMod#89]
对手和自己都没有效果，模拟拔线后也没有变化，皮肤能正常更新，目前仅尝试了狗头人，这也许是一个bug？

**Comment by HiddenCirno** [comment]
女巫森林也无效, 难道是随机冒险都用不了?

**Comment by Pik-4** [comment]
暂无发现该问题

**Comment by HiddenCirno** [comment]
> 暂未发现该问题

![image](https://github.com/user-attachments/assets/a4f6ec70-38ee-4734-b747-e48376a00596)
![image](https://github.com/user-attachments/assets/dab691f3-a071-4102-9989-c2906140c2bc)

**Comment by HiddenCirno** [comment]
> 暂未发现该问题

![image](https://github.com/user-attachments/assets/5d642ec5-7224-48f3-bfcc-9a2577c068ed)
呃, 异画生效了, 但是金卡金头没有效果......

**Comment by Pik-4** [comment]
89#issuecomment-2407717776 

金卡特效没开

**Comment by Pik-4** [comment]
最高，特指钻石，后面添加的异画是被硬塞进来的
