### ISSUE TITLE
请问炉石里skin id应该如何获取

### ISSUE THREAD

**Issue by Parasolation** [Pik-4/HsMod#9]
请问是否有个数据库可以知晓各个皮肤的id，hsmod的显示id功能我无法使用

**Comment by Pik-4** [comment]
显示ID需要手动开启，开启后右键卡牌会有提示。此外还以访问http://127.0.0.1:58744（激活插件的情况下，启动炉石后浏览器访问）看皮肤相关。此外新版本暂未更新，部分功能可能存在异常。

**Comment by Parasolation** [comment]
感谢解答
