### ISSUE TITLE
绕过战网启动炉石客户端第一次可以，退出炉石后再启动就不行了，不知道为什么

### ISSUE THREAD

**Issue by httpsColon** [Pik-4/HsMod#92]
此时访问那个token链接，还是跳转为localhost的

**Comment by httpsColon** [comment]
看了token值也没变啊，CN-xxxxx-xxx的

**Comment by freechao123** [comment]
我看老外老外网站可以不开hsnod也可以绕过战网登录，但我没成功，必须要插件启用才能绕过战网启动炉石

**Comment by freechao123** [comment]
> 此时访问那个token链接，还是跳转为localhost的

现在插件不能用，你也可以绕过战网登录炉石吗

**Comment by Pik-4** [comment]
没看懂你在说啥

**Comment by freechao123** [comment]
> 没看懂你在说啥

大佬，绕过战网启动可以再详细点吗？config文件还是需要的吧，4p里说的也是修改config，但是我试了还是需要插件启用才行

**Comment by httpsColon** [comment]
> 没看懂你在说啥

就是在炉石客户端快捷方式后面加token参数，第一次确实有效，之后就不行了，还是会拉起战网客户端

**Comment by freechao123** [comment]
> > 没看懂你在说啥
> 
> 就是在炉石客户端快捷方式后面加token参数，第一次确实有效，之后就不行了，还是会拉起战网客户端

你是在快捷方式哪里加的，我和你的方式不同，我在config里加的

**Comment by Pik-4** [comment]
无法复现
